### ISSUE TITLE
Flappy3DS

### ISSUE THREAD

**Issue by Komas19-new** [Universal-Team/db#100]
### Title

Flappy3DS

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0x1337

### Image link

None for now.

### Icon link

https://github.com/Komas19-new/flappy3DS/raw/main/icon.bin

### Long description

Just an flappy bird clone for 3ds, no need for an long description right?

### Screenshots

None for now.

### GitHub repository of the app

https://github.com/Komas19-new/flappy3DS

### Author

Komas19

### Short description

Flappy3DS is an Flappy Bird clone for 3DS

### Source code link

https://github.com/Komas19-new/flappy3DS

### Creation date

Nov 10, 2022, 8:18 PM GMT+1

### Last update date

Nov 13, 2022, 8:28 PM GMT+1

### Website link

None for now

### Wiki link

None for now

### Download page link

https://github.com/Komas19-new/flappy3DS/releases

### Version number

v0.1.5.5

### Version title

Flappy3DS v0.1.5.5

### Download link(s)

https://github.com/Komas19-new/flappy3DS/raw/main/flappy.cia
https://github.com/Komas19-new/flappy3DS/raw/main/flappy.3dsx

### Other notes

The invisible banner and the visible icon is temporary, i might change them soon.
Some stuff are not working yet, such as the death count, should work again within version 0.2
In places other than inside the game, it identifies itself as Flappy Pixel, it should be switched to Flappy3DS, with an new icon and banner, within version 1.0

More info: https://github.com/Komas19-new/flappy3DS/blob/main/README.md
The README.md includes an installation process, in case the Universal Updater installation breaks. Also includes an building process to build the app from the source code.

### Developer permission

- [x] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
PS. You shouldn't commit the `build` folder fyi, just bloats up the repo for no reason. You can make a folder called `.gitignore` with things to ignore like
```gitignore
build
*.3dsx
*.cia
*.elf
*.DS_Store
*Thumbs.db
```
or such

**Comment by Komas19-new** [comment]
Ok i just did that, do i remake an request?

**Comment by Komas19-new** [comment]
ok i just removed them

**Comment by Komas19-new** [comment]
i have just made an folder named Compiled and the cia/elf/3dsx will be there, for lazy people

**Comment by Epicpkmn11** [comment]
You don't need to remake the request or anything, I've already added it and this doesn't affect that, was just letting you know that's not a great thing to do since i noticed it while looking at the repo

I wouldn't recommend putting any compiled  binaries at all in the repo as git just isn't great for binary files. It's best to just put compiled binaries in releases and if you want them for every commit you can set up GitHub Actions to automatically build them fyi

**Comment by Komas19-new** [comment]
but the issue is, at the readme.md there is an qr code, and the qr code will link to Compiled/flappy.cia so what do i do?

**Comment by Epicpkmn11** [comment]
If you make a non-pre release you can link to https://github.com/Komas19-new/Flappy3ds/releases/latest/download/flappy.cia or so

you can also just use the Universal DB QR codes if you want: https://db.universal-team.net/assets/images/qr/prerelease/flappy-cia.png

(https://db.universal-team.net/assets/images/qr/flappy-cia.png for stable release)

**Comment by Komas19-new** [comment]
ok, i have also made an dev branch, and this branch will have an qr code, that gets updated always to the newest commit, without making an release

**Comment by Komas19-new** [comment]
also https://github.com/Komas19-new/Flappy3ds/releases/latest/download/flappy.cia shows that it doesn't exist

**Comment by Epicpkmn11** [comment]
It didn't work for prereleases

**Comment by Komas19-new** [comment]
sad
