### ISSUE TITLE
cynanogen 3ds

### ISSUE THREAD

**Issue by Randomeder** [Universal-Team/db#107]
### Title

cynanogen 3ds (i think)

### System(s)

3DS

### Categories

Emulator

### Other notes

plz google it

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by CyberYoshi64** [comment]
Wow, so much nothing. Incredible.
Jokes aside, that's not how you submit apps to Universal-DB. You have to provide the source code and compiled binaries so it could be added. Just saying "plz google it" makes me think you neither created that app, nor have permission to submit it here.
