### ISSUE TITLE
StarCruiser7

### ISSUE THREAD

**Issue by dotMizi** [Universal-Team/db#108]
### Title

StarCruiser7

### System(s)

3DS

### Categories

Game

### Icon link

https://raw.githubusercontent.com/dotMizi/StarCruiser7/main/logo.png

### Long description

Star Cruiser 7 is an homage to the late 70s game Star Raiders by Doug Neubauer, published by Atari. It is a Star Raiders-like remake for the Nintendo 3DS game console. My goal was to bring this milestone in the development of computer and console games a bit into the modern era, while maintaining the character and simplicity of this iconic 8-bit game and still using specific features of the 3DS console such as 3D screen, two displays, a faster CPU or the touch function. Even though diving through a star field is by no means realistic, it achieved a wonderful 3d effect on the Atari and this still works on the 3DS. Therefore, this unrealistic effect has been preserved. It should feel like you are playing the game on an Atari 400 home computer, but it should be as much fun as a real 3DS game.

### Screenshots

![start](https://user-images.githubusercontent.com/114505954/206872124-ee9e1db3-8c28-44b9-81b3-6b5945a32455.gif)
![docking](https://user-images.githubusercontent.com/114505954/206872125-71883941-8247-47e2-a80e-383009410864.gif)
![hyperwarp](https://user-images.githubusercontent.com/114505954/206872127-7a11eee9-f003-45ff-a22d-23c87fdbf482.gif)
![shot1](https://user-images.githubusercontent.com/114505954/206872128-cd863fe2-2729-4084-9afe-47dfc3b1da18.gif)

### GitHub repository of the app

https://github.com/dotMizi/StarCruiser7

### Author

dotMizi

### Short description

StarCruiser7 is a first-person space combat simulator for the 3DS game console

### Source code link

https://github.com/dotMizi/StarCruiser7

### Creation date

2022-10-10

### Last update date

2022-12-01

### Website link

https://github.com/dotMizi/StarCruiser7

### Wiki link

https://gbatemp.net/threads/starcruiser7.620148/

### Download page link

https://github.com/dotMizi/StarCruiser7

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
fyi it works better if you put the 3DSX in [a release](https://github.com/dotMizi/StarCruiser7/releases) instead of the repo itself

I can still add it with it there but releases get version tracking and such so the last update date can be tracked automatically and prevent your repo from getting really bloated

**Comment by dotMizi** [comment]
Thank you! I've added a release.
