### ISSUE TITLE
FBI French translations

### ISSUE THREAD

**Issue by cooolgamer** [Universal-Team/db#109]
### Title

FBI-FR

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xF8001 (the same as regular fbi)

### Icon link

https://github.com/cooolgamer/FBI-Reloaded-FR/raw/master/meta/icon_fr.png

### Long description

# Fonctionnalités

* Navigation et modification de la carte SD, TWL sound, TWL photo, sauvegardes et sauvegardes aditionnelles.
* Exporter, Importer, et effacer les sauvegardes de cartouches DS.
* Exporter, Importer, et effacer les Secure Values des sauvegardes (anti-restoration de sauvegarde).
* Installer des titres/tickets depuis un système de fichier, depuis un réseau ou depuis internet avec une URL ou un QRcode.
  * Importe automatiquement la seed d'un titre après son installation depuis internet ou la carte SD.
* Navigation et effacement des titres en attente (mise à jours téléchargés, titres en cours de téléchargement sur l'eshop, etc).
* Customisation de l'apparence en remplaçant les ressources des RomFS dans "sdmc:/fbi/theme/".

* Seulement disponible avec Luma3DS:
  * Navigation et modification de la CTR NAND, TWL NAND, et sauvegardes système.
  * Copier l'image de la NAND dans la carte SD.
  * Démarrer les titres installés dans la console.

### Screenshots

https://github.com/cooolgamer/FBI-Reloaded-FR/blob/master/meta/screenshot.bmp

### GitHub repository of the app

https://github.com/cooolgamer/FBI-Reloaded-FR/

### Author

Steveice10, yogsoy, Zora, cooolgamer

### Short description

Gestionnaire de titre 3DS Open source.

### Source code link

https://github.com/cooolgamer/FBI-Reloaded-FR/

### Creation date

16/12/2022

### Last update date

16/12/2022

### Download page link

https://github.com/cooolgamer/FBI-Reloaded-FR/releases/

### Version title

based on 2.6.1

### Download link(s)

https://github.com/cooolgamer/FBI-Reloaded-FR/releases/download/1.0/FBI-FR.3dsx
https://github.com/cooolgamer/FBI-Reloaded-FR/releases/download/1.0/FBI-FR.cia
https://github.com/cooolgamer/FBI-Reloaded-FR/releases/download/1.0/FBI-FR_Sombre.3dsx
https://github.com/cooolgamer/FBI-Reloaded-FR/releases/download/1.0/FBI-FR_Sombre.cia

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Added in 490802399ce7ef0c1c111e2092aaa8da2265e5d7
