### ISSUE TITLE
Parkin'Rampage

### ISSUE THREAD

**Issue by DesperateProgrammer** [Universal-Team/db#11]
**Name of the app**
Parkin'Rampage

**System(s)**
DS

**Categories**
Game, Puzzle

**Image link**
https://raw.githubusercontent.com/DesperateProgrammer/ParkingRampage/main/gfx/title.png

**Icon link**
https://raw.githubusercontent.com/DesperateProgrammer/ParkingRampage/main/icon.bmp

**Long description**
Navigate the police out of the jammed parking lot!

**Screenshots**

**GitHub repository of the app**
https://github.com/DesperateProgrammer/ParkingRampage

**Author**
Tim 'Mighty Max' Seidel

**Short description**
A classic puzzle game. Your goal is to move all cars out of the way, so the üolice can leave the parking lot.

**Source code link**
https://github.com/DesperateProgrammer/ParkingRampage

**Creation date**
18.12.2020

**Last update date**
02.01.2021

**Website link**
https://mighty-max.itch.io/parkin-rampage

**Wiki link**

**Download page link**
https://github.com/DesperateProgrammer/ParkingRampage

**Version number**
02012021

**Version title**
Parkin'Rampage 02012021

**Last update date**
02.01.2021

**Download link(s)**
https://github.com/DesperateProgrammer/ParkingRampage/raw/main/ParkingRampage.nds

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
fyi If you could make a release on GitHub with the download attached that'd make adding this a little easier since the download links and version tracking and all that would be automatic in case you make an update in the future, I can still add it without though if you'd prefer not to
