### ISSUE TITLE
Space Game: App request

### ISSUE THREAD

**Issue by BiberGames** [Universal-Team/db#113]
### Title

Space Game

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0xFF3FF

### Image link

https://raw.githubusercontent.com/BiberGames/Space-Game/main/Banner.png

### Icon link

https://raw.githubusercontent.com/BiberGames/Space-Game/main/Icon.png

### Long description

A simple game about avoiding meteorides in space.
Circle pad for avoiding meteorites.

Sprites:
	https://www.flaticon.com/free-icon/rock_3413211?term=asteroid&page=1&position=9&origin=search&related_id=3413211
	https://www.flaticon.com/free-icon/spaceship_8851089?related_id=8851089
	https://www.flaticon.com/de/kostenloses-icon/star_616655?term=star&page=1&position=20&origin=search&related_id=616655
	https://www.flaticon.com/free-icon/explosion_599698?term=explosion&page=1&position=5&origin=search&related_id=599698
	https://www.flaticon.com/free-icon/health-care_3632599?term=health&page=1&position=36&origin=search&related_id=3632599
	
Music / Sounds:
	https://www.youtube.com/watch?v=thnXzUFJnfQ
	https://freesound.org/people/Robinhood76/sounds/584119/
	https://freesound.org/people/TROLlox_78/sounds/274119/
	https://freesound.org/people/juancamiloorjuela/sounds/204318/

### Screenshots

![screen1](https://raw.githubusercontent.com/BiberGames/Space-Game/main/screen1.png)
![screen2](https://raw.githubusercontent.com/BiberGames/Space-Game/main/screen2.png)

### GitHub repository of the app

https://github.com/BiberGames/Space-Game

### Author

Benjamin

### Short description

A game about avoiding meteorides in space.

### Creation date

17. January 2023

### Last update date

17. January 2023

### Download page link

https://github.com/BiberGames/Space-Game/releases/tag/v1.0

### Version number

v1.0

### Version title

First version :)

### Download link(s)

https://drive.google.com/file/d/1OO7Ux5-SncVwHBmD9aH0pzO4qZjvuyPf/view?usp=share_link
https://github.com/BiberGames/Space-Game/releases/download/v1.0/spacetest.7z

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
I see you marked the unique ID as 0xFF3FF, that's the default ID do I'd highly suggest changing it fyi

I'd also suggest publishing the source code, though we don't strictly require everything to be open source

either way I'll add this tonight my time when I've got some time 👍

**Comment by BiberGames** [comment]
Thanks for the response :)
I change the ID tomorrow, source code needs to be cleaned up.

> I see you marked the unique ID as 0xFF3FF, that's the default ID so I'd highly suggest changing it fyi
> 
> I'd also suggest publishing the source code, though we don't strictly require everything to be open source
> 
> either way I'll add this tonight my time when I've got some time 👍

**Comment by Tobi-D7** [comment]
Don't Add this!
Its Made with Unity!

1:
3gxloader reacts on it
2:
Only Cia and no source code
3:
There are a lot of Unity Assetfiles in the Romfs 
![image](https://user-images.githubusercontent.com/71647024/213011911-8de0c299-0748-4285-8cb3-3043e08c3582.png)
![image](https://user-images.githubusercontent.com/71647024/213012185-1adbe71f-a0db-4af1-af24-b119c1194826.png)

**Comment by NightScript370** [comment]
Thanks for telling us. I'll close this issue.

**Comment by Tobi-D7** [comment]
No Problem :)
