### ISSUE TITLE
Add CrossCraft 3DS

### ISSUE THREAD

**Issue by susbaconhairman** [Universal-Team/db#114]
### Title

CrossCraft 3DS

### System(s)

3DS

### Categories

Game

### Long description

An attempted port of Classic Java Minevcraft to the 3DS, can be found here: https://github.com/CrossCraft/CrossCraft-Classic/releases It is a 3DSX only.

### GitHub repository of the app

https://github.com/CrossCraft/CrossCraft-Classic/

### Author

Cross Craft Team

### Short description

CrossCraft-Classic is a project that implements Minecraft Java Edition: Classic without looking at any of the source code of the original application and without using the original copyrighted assets.

### Source code link

https://github.com/CrossCraft/CrossCraft-Classic/releases

### Creation date

December 1st, 2022

### Last update date

December 1st, 2022 (first 3DS build was on that date)

### Website link

https://github.com/CrossCraft

### Download page link

https://github.com/CrossCraft/CrossCraft-Classic/releases

### Version number

v1.3

### Version title

End of the Line

### Download link(s)

https://github.com/CrossCraft/CrossCraft-Classic/releases/download/v1.3/CrossCraft-3DS.zip

### Other notes

Please add it
I'm not a developer of the app either

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Added in 34787688da0784cda392075b66f9a6c993c36afa
