### ISSUE TITLE
Add 3hs app

### ISSUE THREAD

**Issue by Minionguyjpro** [Universal-Team/db#115]
### Title

3hs

### System(s)

3DS

### Categories

Utility

### Image link

https://raw.githubusercontent.com/MyPasswordIsWeak/3hs/master/cia_stuff/banner.png

### Icon link

https://github.com/MyPasswordIsWeak/3hs/blob/master/cia_stuff/icon.png

### GitHub repository of the app

https://github.com/MyPasswordIsWeak/3hs

### Author

hShop

### Short description

3hs is a brand new application developed from the ground up and designed to allow installing content from hShop on your 3DS directly, omitting the need to use FBI every time.

### Website link

https://hshop.erista.me/

### Download page link

https://hshop.erista.me/3hs

### Other notes

I just want to let the app at. No more.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Minionguyjpro** [comment]
Nevermind, this is actually not allowed.

**Comment by Tobi-D7** [comment]
Why requesting this?

It is obviously illegal...
