### ISSUE TITLE
I want to submit my app

### ISSUE THREAD

**Issue by TheHighTide** [Universal-Team/db#117]
### Title

HighTide General App

### System(s)

3DS

### Categories

Utility

### Image link

https://hightide.coolpage.biz/Resources/Images/3DS/HTHA/banner.png

### Icon link

https://hightide.coolpage.biz/Resources/Images/3DS/HTHA/icon.png

### HighTide Homebrew App
The **HighTide Homebrew App** is an amazing app that will allow you to see a bunch of technical info about your system. This app will continue to be updated as it is small right now. More features will be added!

### Author

TheHighTide

### Short description

The sys info app by HighTide

### Creation date

2023-02-12

### Last update date

2023-02-12

### Download link(s)

https://hightide.coolpage.biz/Resources/Images/3DS/HTHA/HighTideHomebrewApp.3dsx

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Apologies for the delay, your webpage where the 3DSX was hosted appears to have been deleted so unfortunately I cannot add this at the moment

I would recommend using GitHub releases for hosting (and publishing the source code as well), they allow unlimited files up to 2 GB with no expiration and easy access

Please feel free to reopen if the download is fixed
