### ISSUE TITLE
Add Rehid

### ISSUE THREAD

**Issue by bigskribbz** [Universal-Team/db#121]
### Title

Rehid

### System(s)

3DS

### Categories

Utility

### Icon link

The 3dsx has an image that displays as part of the preview in the hb

### Long description

# Rehid

HID module rewrite with the aim of easier button remapping and more.

## How To Use

You need to have the latest luma for this to work correctly.

* Download `rehidhelper.3dsx` from the latest release
* Open homebrew launcher and run the 3dsx
* Click `A` on the `Download Rehid` option
* Restart your 3ds
* Go to https://mikahjc.github.io/3dsRemapBuilder/config and generate your remappings.
* Run rehidhelper again and select the Scan QR code option
* Scan your QR.

## How To Remap Buttons

You first need to create a `rehid.json` file with the remappings you want. For eg:-
```Json
{
    "keys":[
        {"get":"R", "press":"ZR"},
        {"get":"L", "press":"ZL"}
    ]
}
```
With the above, everytime you press `ZR` key, `R` key would be triggered, 

and everytime you press `ZL` key, `L` key would be triggered.

It is also possible to do custom key combos, i.e.,
```Json
{
    "keys":[
        {"get":"R", "press":"X+Y"},
        {"get":"L+R", "press":"SELECT"}
    ]
}
```
Now everytime you press `X+Y`, `R` key would be triggered and on pressing `SELECT` button, both `L` and `R` would be triggered.

Possible Keys are:- 
`A`, `B`, `X`, `Y`, `SELECT`, `START`, `ZL`, `ZR`, `L`, `R`, `LEFT`, `RIGHT`, `UP`, `DOWN`, `CRIGHT`(CPAD), `CLEFT`(CPAD), `CUP`(CPAD), `CDOWN`(CPAD)

Copy your `rehid.json` file to the `rehid` folder.

### Per Title Button Remapping

It is possible to have different button remapings for different titles:-

Inside the `rehid` folder, create a folder with the titleid as the folder name.

You can use [this](https://hax0kartik.github.io/3dsdb/) to fidn the titleid for your game.

Copy the `rehid.json` file inside this folder.

## Compilation
Get devkitpro, ctrulib and makerom and then `make -j` to compile.

## Credits

@luigoalma Help, testing and listening to my rants.

Druivensap on my discord server for helping me test out.

Luma3ds devs and contributors

### Screenshots

https://www.gamebrew.org/thumb.php?f=Rehid2.png&width=300

### GitHub repository of the app

https://github.com/hax0kartik/rehid

### Author

hax0kartik

### Short description

HID module rewrite with the aim of easier button remapping and more

### Source code link

https://github.com/hax0kartik/rehid

### Creation date

Nov. 7th, 2020

### Last update date

Jun. 7th, 2021

### Website link

https://mikahjc.github.io/3dsRemapBuilder/config

### Download page link

https://github.com/hax0kartik/rehid/releases/

### Version number

3.0

### Version title

Fourth Release

### Download link(s)

https://github.com/hax0kartik/rehid/releases/

### Other notes

Maps must be created with this website; https://mikahjc.github.io/3dsRemapBuilder/config
There are also some pre-made maps here: https://github.com/Nanashi13/Rehid-configs-files-3DS maybe they could be added in the downloads page for Rehid, or as an entirely new entry?

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
rehid is already [on Universal-DB](https://db.universal-team.net/3ds/rehid), but I'll add your metadata since it's currently rather a blank page

**Comment by Epicpkmn11** [comment]
> The 3dsx has an image that displays as part of the preview in the hb

That's the default 3DSX icon, I don't use generic icons on Universal-DB as it's not helpful for identifying the app
