### ISSUE TITLE
Yet another ThirdTube translation (this time German)

### ISSUE THREAD

**Issue by Frocat64** [Universal-Team/db#123]
### Title

ThirdTube-DE

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xBF74D

### Image link

https://github.com/Frocat64/ThirdTube-DE/blob/main/resource/banner.png

### Icon link

https://github.com/Frocat64/ThirdTube-DE/blob/main/resource/icon.png

### GitHub repository of the app

https://github.com/Frocat64/ThirdTube-DE

### Author

windows-server

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
Y'all (CC @cooolgamer @FreakinSoftMania) might want to try just PR'ing your translations to the official version, took a look at the code and looks like the app is set up for languages fine

I'll still add this for now, but it's getting a bit crazy on the ThirdTube translations lol

**Comment by Epicpkmn11** [comment]
Added in a9e799f0c93c5cc8d5fc11ab3b1a8d8a09665f45
