### ISSUE TITLE
clean perfect WarioWare - Do It Yourself (USA, Europe) DLC and Wii saves, for noobs.

### ISSUE THREAD

**Issue by ghost** [Universal-Team/db#126]
[warioware d.i.y. - wii content + dlc clean no cheats and progress saves.zip](https://github.com/Universal-Team/db/files/10977555/warioware.d.i.y.-.wii.content.%2B.dlc.clean.no.cheats.and.progress.saves.zip)
the Official DLCs and the Wii content are all finally in clean DS save form (no cheats and progress infections), designed for newcomer noobs who don't know how to or are too lazy to inject mio files into the saves.

all the saves here are compatible with both the USA and Europe versions of the roms.

**Comment by bigskribbz** [comment]
Why do wii need stuff for the Wii if this is a 3ds/ds store?

**Comment by HiredSylvain** [comment]
this is pretty much actually the ds saves mislabled as wii's saves. also could this issue be deleted as well, nothing to do with the universal updator.
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .sav real hardware form.zip](https://github.com/Universal-Team/db/files/11007739/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.sav.real.hardware.form.zip)
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .dsv drastic form.zip](https://github.com/Universal-Team/db/files/11007738/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.dsv.drastic.form.zip)

**Comment by HiredSylvainFE** [comment]
Fuck you NightScript370, delete this fucking issue and burn it in fucking hell already, fuck you for not deleting these two issues, even clearly sent the link to say delete them and you didn't even fucking listen.

**Comment by HiredSylvainFE** [comment]
Delete this issue already

**Comment by HiredSylvainFE** [comment]
Fuck you and delete this issue do it do it already

**Comment by NightScript370** [comment]
Deleting it would give you what you want. I'd rather let you drown in your ligma disease.
