### ISSUE TITLE
ChatGPT3DS

### ISSUE THREAD

**Issue by CarsonKompon** [Universal-Team/db#127]
### Title

ChatGPT3DS

### System(s)

3DS

### Categories

Utility

### Image link

https://i.imgur.com/7iRHxNb.png

### Icon link

https://i.imgur.com/boRnbaA.png

### Long description

Make calls to OpenAI's chat completion and image generation API. Requires an OpenAI account with billing set up.

### Screenshots

![](https://i.imgur.com/fN7Hy26.png)
![](https://i.imgur.com/xPx3eKp.png)
![](https://i.imgur.com/PLZaTvP.png)
![](https://i.imgur.com/m4D7EYn.png)

### GitHub repository of the app

https://github.com/CarsonKompon/ChatGPT3DS

### Short description

Make calls to OpenAI's chat completion and image generation API.

### Other notes

Requires an OpenAI API Key: https://platform.openai.com/account/api-keys

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by bigskribbz** [comment]
Please add this team!

**Comment by bigskribbz** [comment]
LoL stupid ai really just said hacking was illegal
