### ISSUE TITLE
could https://github.com/Universal-Team/db/issues/126 and this issue be deleted much like https://github.com/Difegue/DoujinSoft/issues/26

### ISSUE THREAD

**Issue by ghost** [Universal-Team/db#129]
basically https://github.com/Universal-Team/db/issues/126 this are just troll trash pages with the good saves buried in them, could issue #126 be deleted much like https://github.com/Difegue/DoujinSoft/issues/26 and openemu's issue page deleting troll pages too.
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .dsv drastic form.zip](https://github.com/Universal-Team/db/files/11007749/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.dsv.drastic.form.zip)
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .sav real hardware form.zip](https://github.com/Universal-Team/db/files/11007750/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.sav.real.hardware.form.zip)

**Comment by bigskribbz** [comment]
That's crazy :skull:

**Comment by NightScript370** [comment]
Next time, comment on the actual issue rather than making a new one.

**Comment by HiredSylvainFE** [comment]
Motherfuckers, I fucking said delete this and https://github.com/Universal-Team/db/issues/126 issues, not just close them, you fuckers you can clearly see the link where a issue was deleted, why can't you guys do that too?, this is a motherfucking death threat, if you guys won't delete these two issues, I'm going to spam flood this issue  tab.

**Comment by HiredSylvainFE** [comment]
Do it do and fucking delete this fuck of a issue

**Comment by HiredSylvainFE** [comment]
Delete all these "my" troll issues on this database and universal updator
