### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by eqagunn** [Universal-Team/db#13]
**Name of the app**
Checkpoint

**System(s)**
3DS

**Categories**
Utilities

**Icon link**
https://static.wiidatabase.de/Checkpoint-Switch-neu.jpg

**Long description**
A fast and simple homebrew save manager for 3DS and Switch written in C++.

**Screenshots**
https://camo.githubusercontent.com/727083817d0f28928ec77306c762cf3155f7fc55d698738da1b0114df760a213/68747470733a2f2f692e696d6775722e636f6d2f5934784a6948732e706e67

**GitHub repository of the app**
https://github.com/FlagBrew/Checkpoint

**Download link(s)**
https://github.com/the-conceptionist/universal-updater-scripts/blob/master/Checkpoint.json

- [ ] I am the app developer or have permission from the app developer to make this request
- [x] I am not the app developer and I haven't ask him for permission to make this request

**Comment by Epicpkmn11** [comment]
FlagBrew have asked to not have their apps included on 3rd party sites like this so we won't be adding any of their apps.

**Comment by BernardoGiordano** [comment]
This is now resolved.
