### ISSUE TITLE
3gx luma repo has changed

### ISSUE THREAD

**Issue by MechanicalDragon0687** [Universal-Team/db#130]
https://github.com/Universal-Team/db/blob/22f4fea7200e65078deb3fd8bd26f4be0aa21149/source/source.json#L3711

https://github.com/PabloMK7/Luma3DS_3GX

we updated our tag in the NH server, probably ought to fix it here too 
![image](https://user-images.githubusercontent.com/43786828/229925662-1879c8ea-8b30-4b51-be07-ac8c303b0f9e.png)

**Comment by Epicpkmn11** [comment]
Renamed in 8fca392c6b1047a0887028f0524ea24b6ba561f4, note that I changed the Universal-DB name to [Luma3DS (3GX)](https://db.universal-team.net/3ds/luma3ds-3gx)
