### ISSUE TITLE
hShop

### ISSUE THREAD

**Issue by RubennRmPro** [Universal-Team/db#132]
### Title

hShop

### System(s)

3DS

### Categories

Utility

### Long description

Freeshop to download themes,games,dlcs and more.

### GitHub repository of the app

https://github.com/RubennRmPro/hShop/blob/main/3hs.cia

### Author

hShop

### Short description

FreeShop.

### Creation date

4/22/2023

### Last update date

4/22/2023

### Website link

https://github.com/RubennRmPro/hShop/

### Download page link

https://github.com/RubennRmPro/hShop/blob/main/3hs.cia?raw=true

### Version number

1.10.4

### Version title

1.10.4

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by lifehackerhansol** [comment]
Since when were you the main developer of this app

**Comment by Epicpkmn11** [comment]
We don't support piracy
