### ISSUE TITLE
Minecraft 3DS UniStore

### ISSUE THREAD

**Issue by susbaconhairman** [Universal-Team/db#137]
### Title

Minecraft 3DS Customization

### System(s)

3DS

### Categories

Utility

### Long description

No pirated content or stuff I haven't gotten permission for to add in the store

Please add this in the recommended unistores section

### GitHub repository of the app

https://github.com/susbaconhairman/minecraft-3ds-unistore/

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by susbaconhairman** [comment]
And I promise I'll be good!!

**Comment by NightScript370** [comment]
Last time we removed it, you sent the following messages alongside it

> i could care less about them removing it
> i dont know why they didnt remove my unistore when i was banned anyway

You're still banned, so according to your logic, your stuff shouldn't be on our server.

The reason your ban is still present is self evident by your awful attitude, which you yourself displayed on our repo last week.

Short answer: no.
Goodbye

**Comment by susbaconhairman** [comment]
ouchie :fire:
