### ISSUE TITLE
Sonic CD 3DS Redux

### ISSUE THREAD

**Issue by jameslandon786** [Universal-Team/db#138]
### Title

Sonic CD 3DS Redux

### System(s)

3DS

### Categories

Game

### Unique ID(s)

00040000072F0300

### Image link

https://gbatemp.net/attachments/banner-png.351272/

### Icon link

https://cdn2.steamgriddb.com/file/sgdb-cdn/icon/80537a945c7aaa788ccfcdf1b99b5d8f/32/48x48.png

### Long description

Hi there. Today, I'm happy to share with you all a newer, up-to-date 3DS Port of the Sonic CD (2011) decompilation project by Rubberduckycooly and others.
It uses Citro3D for the graphics backend, SDL 1.2 for the audio backend, among the usual dependencies.
Features:

    Built on the most recent decomp code base (as of Feb 2023)
    Runs full speed on both O3DS and N3DS!
    Stereoscopic 3D support
    No laggy/slow special stages
    (Hopefully) less crash-prone than the other existing 3DS port
    Remappable (keyboard) keys in settings.ini (Uses [bitmasks](https://github.com/devkitPro/libctru/blob/master/libctru/include/3ds/services/hid.h) from libctru)
    And just like the other port, dev menu can be accessed at any time by pressing SELECT

Setup:

    You need to [dump the DSP firm](https://github.com/zoogie/DSP1/releases) before running the game, otherwise there will be no audio.
    Using Data.rsdk from the mobile version is highly recommended; with the non-mobile Data.rsdk, special stage floor tiles are broken and Tidal Tempest has trouble rendering at all.
    Just copy `SonicCD.3dsx` (or install `SonicCD.cia`) and `Data.rsdk` to `/3ds/SonicCD/` on the SD card.
    Don't copy over an existing settings.ini; this might result in unexpected issues (i.e. no input). Just let a new settings.ini be generated on first startup before modifying anything in the config.
    FMVs are currently unsupported, so don't bother copying them. You'll only need the Data.rsdk for now.

Currently Unsupported:

    There's currently an issue where the title screen won't respond to button inputs when using the iOS Data.rsdk. To work around this, either access the main menu via the dev menu or switch to using the Android Data.rsdk.
    Mods (linker error when trying to compile the relevant code (undefined reference to `pathconf` in a part of std::fs))
    FMVs

### Screenshots

https://gbatemp.net/attachments/_05-02-23_11-08-44-739-png.351290/
https://gbatemp.net/attachments/_05-02-23_11-11-40-249-png.351292/
https://gbatemp.net/data/attachments/350/350681-e1872120915c5593a0dda8b630417092.jpg

### GitHub repository of the app

https://github.com/Voxel9/Sonic-CD-11-3DS-Redux

### Download link(s)

https://github.com/Voxel9/Sonic-CD-11-3DS-Redux/releases/download/v1.1.0/SonicCD.cia
https://github.com/Voxel9/Sonic-CD-11-3DS-Redux/releases/download/v1.1.0/SonicCD.3dsx

### Other notes

Setup:

    You need to [dump the DSP firm](https://github.com/zoogie/DSP1/releases) before running the game, otherwise there will be no audio.
    Using Data.rsdk from the mobile version is highly recommended; with the non-mobile Data.rsdk, special stage floor tiles are broken and Tidal Tempest has trouble rendering at all.
    Just copy `SonicCD.3dsx` (or install `SonicCD.cia`) and `Data.rsdk` to `/3ds/SonicCD/` on the SD card.
    Don't copy over an existing settings.ini; this might result in unexpected issues (i.e. no input). Just let a new settings.ini be generated on first startup before modifying anything in the config.
    FMVs are currently unsupported, so don't bother copying them. You'll only need the Data.rsdk for now.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by susbaconhairman** [comment]
I will be sure to add this on my handy dandy 3ds game ports guide, good thing i already have the game files L.O.L!!!!!!!1!!
https://rentry.org/3ds-game-ports-guide

**Comment by NightScript370** [comment]
@Voxel9 thank you for informing us regarding that.
I am going to close the issue.

Just so I'm aware, are you also the manager of the other sonic ports? Are they fine on the store?

**Comment by Voxel9** [comment]
@NightScript370 Hi, I'm not. This is the only port that I developed and manage.

**Comment by jameslandon786** [comment]
I am so sorry for this. I tried messaging you on GBATemp, and I guess it
didn't work, and for some reason, at like 2 AM, I just thought, "Fuck it,
might as well try" and just did it without any second thought. Again I am
really sorry for this.

**Comment by Voxel9** [comment]
It's all cool dude, I'm not mad or anything, just had plans to submit it myself eventually and realized I was about to be beaten to the punch without even knowing 😅
Ah, yeah I didn't get any message on GBAtemp. How strange.

**Comment by jameslandon786** [comment]
Alright, sick. 😁
