### ISSUE TITLE
[Uxnds 3DS] Request to consider adding this micro computer emulator

### ISSUE THREAD

**Issue by RE4PERX6** [Universal-Team/db#142]
### Title

Uxnds 3DS

### System(s)

3DS, DS

### Categories

Emulator

### Image link

Don't have one since is homebrew

### Icon link

![image](https://raw.githubusercontent.com/asiekierka/uxnds/main/misc/uxn48.png)

### Long description

Unxds is a port of the [Unx virtual machine](https://wiki.xxiivv.com/site/uxn.html) to the 3DS. Uxn is a portable 8-bit virtual computer inspired by [forth-machines](https://en.wikipedia.org/wiki/Forth_(programming_language)), capable of running simple tools and games programmable in its own [assembly language](https://wiki.xxiivv.com/site/uxntal.html).

This emulator allows you run to your uxn projects on the 3DS, it can also be used for developers who want to learn how to program little 8-bit things.

It was designed with an implementation-first mindset with a focus on creating portable graphical applications, the distribution of Uxn projects is akin to sharing game roms for any classic console emulator.

### Screenshots

![image](https://github.com/Universal-Team/db/assets/97109472/e17cd0f9-91e9-4cac-b8e7-f46f9e540616)
![image](https://github.com/Universal-Team/db/assets/97109472/22321930-38b2-4989-afb9-8447630e7b6f)
![image](https://github.com/Universal-Team/db/assets/97109472/efe94769-baa4-4da7-9744-150b765eceb9)
![image](https://github.com/Universal-Team/db/assets/97109472/a09a6b9d-f55f-481d-9cf5-10019cca59d0)
![image](https://github.com/Universal-Team/db/assets/97109472/1d3f9fd8-1978-4e37-a073-216564e3ef46)

### GitHub repository of the app

https://github.com/asiekierka/uxnds

### Author

[asiekierka](https://github.com/asiekierka)

### Short description

Unxds is a port of the Unx virtual machine to the DS/DSi/3DS.

### Source code link

https://github.com/asiekierka/uxnds.git

### Creation date

May 18, 2021

### Last update date

May 8, 2023

### Website link

https://100r.co/site/uxn.html

### Wiki link

https://wiki.xxiivv.com/site/uxn.html

### Download page link

https://github.com/asiekierka/uxnds/releases/tag/v0.4.3

### Version number

0.4.3

### Version title

uxnds 0.4.3

### Download link(s)

[https://github.com/asiekierka/uxnds/releases/download/v0.4.3/uxnds043.zip](url)

### Other notes

**Usage**

By default, uxnds will run /uxn/boot.rom or /uxn/launcher.rom. It also supports reading files from within /uxn.

On start, a keyboard is presented on the bottom screen, and the uxn display - on the top screen. Use the L or R buttons to swap them - in this configuration, mouse input is approximated via touchscreen.

You can use the system button in the lower-left corner to reset the uxn virtual machine.

**Installation**

Two ports are provided: the 3DS port (compatible with 3DS consoles) and the NDS port (compatible with DS, DSi and 3DS consoles).

**3DS port**

There is one binary provided: uxnds.3dsx.

To compile uxnds for 3DS, you may use:

    the latest devkitARM toolchain from the devkitPro organization to compile. After [installing](https://devkitpro.org/wiki/Getting_Started), simply run make -f Makefile.3ds.

**NDS port**

When using a real DS, DSi or 3DS console, it is recommended to launch this program via [nds-hb-menu](https://github.com/devkitPro/nds-hb-menu) - though, as it currently doesn't use argc/argv, it doesn't really change much.

There are three binaries provided:

    uxnds.nds - faster, but best used only with known-good software,
    uxnds_debug.nds - slower, but provides debugging information, profiling information and performs CPU stack bounds checks.
    uxnds_profile.nds - almost as fast as uxnds.nds - with debugging/profiling information, no CPU stack bounds checks.

To compile uxnds for NDS, you may use:

    the [BlocksDS toolchain](https://github.com/blocksds/sdk) - run make -f Makefile.blocksds;
    the latest devkitARM toolchain from the devkitPro organization to compile. After [installing](https://devkitpro.org/wiki/Getting_Started), simply run make -f Makefile.nds.

**About**

NDS/3DS fork/port of the uxn/Varvara virtual machine

**Contributors**

    @asiekierka
    asiekierka Adrian Siekierka
    @DeltaF1
    DeltaF1 DeltaF1
    @Hoolean
    Hoolean Harry Dalton

**Languages**

C 86.9%
Makefile 4.5%
Roff 4.5%
Assembly 3.7%
C++ 0.4%

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by RE4PERX6** [comment]
I am not the owner or have any relationship with the creation of the software, but since it is an open source software, I open the ticket so that you consider contacting the developer and ask for permission to post his app if necessary.

I appreciate your time and apologize in advance for any inconvenience I may have caused.

**Comment by CyberYoshi64** [comment]
That's not how submissions to Universal-DB work. The maintainers of this database are not the ones having to ask permission to use their work, but the submitters (so you). If you tick "I am the app developer or have permission from the app developer to make this request", which you're forced to, that should explain everything.
Next time, when submitting, keep this in mind.

**Comment by RE4PERX6** [comment]
I'm sorry, I should have read more carefully since English is not my native language, I guess I should delete the entry until I talk to the author

**Comment by asiekierka** [comment]
While I am not in the habit of granting explicit permissions - they would count as endorsements, and I cannot endorse a software hosting platform which houses a lot of software which are concerning to me personally from a legal standpoint - uxnds may be redistributed freely if its licensing terms are respected.
