### ISSUE TITLE
Pictochat for 3ds

### ISSUE THREAD

**Issue by Danielcc999** [Universal-Team/db#143]
### Title

Pictochat for 3ds

### System(s)

3DS

### Categories

Utility

### Image link

https://lh3.googleusercontent.com/pw/AIL4fc_wXGP7QXlwUqO30plpIcEaAudq1xAIXkVVD_uOB62-b_r1LFq0NWET-GYKYfJIeLug1K0aQAwqybIDfKhLWSk_sVCGr38B-UXRxMbai7bqdCcDAkaTiQo1fI3Of9vc2JPV2YBfg67WkWZxl3LyF2dKt8mpsjUcx7JhUNsGbQFa-WPEZdLoc4mqd0PzSf4Yb4KyVNONm0UJH5XC3AlEnzQiJVEJfjdEFy5ZIJAu4tdDTl5i-XOR9yfJ2z_7FieXJrGhjqX_iobr0op4y_sYiDc1UKQcSVeTeJRmkdXGDWV6vmrF5OzEGL5QWqU9RxbZUcOETPqPBEBAU2neSGJ2SUCX6Sxt4IDmJee26u6K6AZFVs6EMyisSsMeeMWK3-BIeVdj5aFzUjhdGEUfsemKRJ1S2bqriZHtR_rMA377WRRm5HCHR7LF05ymFssf9qfv4niPj5a3FEJXzV1ipFVrtMoGeqMm1NTk6qp3btGJ4SC9pQvpKMHhA9PovINVdEsGtRbEG3lSsA6o_1UDPEI4vz0QU2Kqm2sk_e-BpnF6Itbtjs0jRJtsG8DC_VEqjG0T8D1oHNiF8cYFdmrVKDSV3ZAV61xwos4_fmlf-4OjtmgeJSA7bnhqL5XXjHBSMGpC1tkzP2Ah_w1I9Qvl8Zb8RgCOuzUTgT1P-uLH5ASTPFFQUwaKkwEB1X-STVLeAiKxKdUNZSjwPiLXqaEjtw3gBNgD9hxSLdraYVlQZHiFQsWRLFeKzCKlHbWHFBSmd1hjzbPoFh1QAua-uoNC8Xh_9tj4kbp8tGfsGpSY_WP0RjoGuQ_lTAQUEozKPQfPdoqM3tLgWiFkcSsW6L9bLGXFAA_JrPJli5PaAvsG4c-J9j7myffBl928AikzAvW1s0bLu5ymnqDFg_WjVgyQ9i3YCq1syF0PQB0kz3kjCaKtD4nv_oqltB6PtxSUOQ__=w686-h386-s-no?authuser=0

### Icon link

https://lh3.googleusercontent.com/pw/AIL4fc-KPh6gf4hKXRiIt_5uF2YtVedrFYUDmaHvJOcNxl518V0fT81jUJ5gbGkBHrZ-ixYs8_JdVD659rvJ8CR4t9-j6z0bUdkLJCZ3RQeZns5e8qa8PwJnyw6PqOfEM4FEVWstFzux4-sfeenx6_V1fVCMicd4rWPMKmNCn6jdKts2Js7yDpjroqK1I72OqI2kTVL0CicbKL5Ukh6iemg0JCULkTqk5mAVHID3wBJFldVmVX2Sio5EbnRaSWMWfJFi_VwOTCe5BChAhWMUujbUjSJw5mprSNtZ05WLAKdcjPwNx-Pa2WCQrQnmvMVgO3Nm4pDSTntcvGQJjib8r_O49xR4brmEy9UowCc169_afqVGeiEJmZ9CTgtoAsHtQty5shHSA6DVEwEKCL2PyGdgpcRom4H9iqzcq96Kr8heqz2MUZ420Pz4mI917STEv3FGKy-jKqb6q_Wm8z61aDYWbEd87ESY1tH2u01vCozeTkOWaLo7T4vRrBeGrsyGdxvhbkU76C2cmn0XhGFiz8om-1j5uKCtlHNKpI15kPGrow4Q5QT9XwkP0L8M9lZF0i8iL5Y0xqYD1fBdLIKv3ihtiio1Ksfp4xTVSY3f7Gnc-rXxe520Mn13IDdNnbFFdGbtT9IGq3s3pdUHjND7gMtrW3bG5_OqasQ_jTtQCMxY3hPC0UADBMMvzIneetg4t3Jg7m56JoXyhrLinU3oBWb8aGree54gA9AVx7mE28vY5K80xM72LjuFUz12qBBU7SvJO1AG-bsXExAY3w7ulTf8KAnUhh0Otq6FfMExABrdoSAuQhj9M-m9zpraFyePspQExzflB6hErZ-QARYFqb06nJv6SLS7y716o-jlhz5WeOjdnV1VbbeFJhsTkAqrfj-UV2j1utYN-ANXtSiNQxcrki2AhEq5wwCxsXHZRnzDLwA-JEv0RR2jNCxxg_np=w32-h32-s-no?authuser=0

### Screenshots

![myc0zrlte3661](https://github.com/Universal-Team/db/assets/43113267/8e251d6f-deba-449a-bdfb-d1f8959c577c)
![TWL_FOM_4c_UKV_SCR144](https://github.com/Universal-Team/db/assets/43113267/140a237c-0245-424f-8a73-e55d10bc698f)

### Author

Nintendo

### Creation date

November 21, 2004

### Last update date

March 22, 2012

### Version number

1.0

### Version title

DSi

### Download link(s)

-snip-
PictoChat cia is in zip.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
This looks like it's just the official PictoChat as a CIA

> 1. Do not include any copyrighted content that you don't have the rights to use (piracy)
