### ISSUE TITLE
Nimbus (Pretendo patches for 3DS)

### ISSUE THREAD

**Issue by TraceEntertains** [Universal-Team/db#144]
### Title

Nimbus

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xD40D2

### Image link

https://raw.githubusercontent.com/PretendoNetwork/nimbus/main/app/meta/banner.png

### Icon link

https://raw.githubusercontent.com/PretendoNetwork/nimbus/main/app/meta/icon.png

### Long description

<p>Usage</p>
<ul>
    <li>Run the Nimbus homebrew and choose to use either a Pretendo or Nintendo account.</li>
</ul>

<p>If the app doesn't work, try the following steps:</p>
<ul>
    <li>Reboot your 3DS while holding SELECT and make sure "Enable loading external FIRMs and modules" and "Enable game patching" are both turned on.</li>
    <li>Ensure that your Luma3DS version is 13.0 or higher.</li>
</ul>

### Screenshots

![image](https://github.com/Universal-Team/db/assets/73800394/fdefbedb-4ad9-4311-9c92-f0b3e3d61dce)
![image1](https://github.com/Universal-Team/db/assets/73800394/65990f36-77cd-4fd3-adde-cf45ac27b9b0)

### GitHub repository of the app

https://github.com/PretendoNetwork/nimbus

### Other notes

Requires minimum of luma 13 and a couple of luma options enabled, but thats included in the long description

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
Really sorry about the slow rate of adding things lately, I've had a lot going on lately so I haven't had the time to review and add these... it's hardly difficult, but I like to review that everything seems decent and make sure I'm including the best info and such so it's not exactly automatic 😅

**Comment by jonbarrow** [comment]
I heard there were some concerns about permission here, so as the project lead that this app is used for:

- I gave permission
- Trace is the one who developed this version of the app

**Comment by TraceEntertains** [comment]
To clarify, I didn't fully develop the latest version of nimbus, but I have been the lead maintainer for a few months now
