### ISSUE TITLE
GodMode9 ITA

### ISSUE THREAD

**Issue by M4nueleZ** [Universal-Team/db#146]
### Title

GodMode9 in Italiano

### System(s)

3DS

### Categories

FIRM

### Long description

GodMode9 è un esplora file per console Nintendo 3DS, che dà pieno accesso alla scheda SD, alle partizioni FAT della SysNAND e EmuNAND e praticamente qualsiasi altra cosa. Tra le varie funzionalità, puoi copiare, eliminare, rinominare file e creare cartelle. Questa è la traduzione italiana dell'originale GodMode9.

### Screenshots

![snap_230811183939](https://github.com/Universal-Team/db/assets/139117311/2a9d0565-bfb6-4329-bdd5-2c33cef5305f)
![logoit](https://github.com/Universal-Team/db/assets/139117311/558f7f92-ef56-42ef-b8df-94230ed9fccb)

### GitHub repository of the app

https://github.com/M4nueleZ/GodMode9_ITA

### Author

M4nueleZ

### Short description

GodMode9 Ed. Italiana - Traduzione italiana dell'originale GodMode9 Explorer per Nintendo 3DS

### Version number

2.1.1.0

### Download link(s)

https://github.com/M4nueleZ/GodMode9_ITA/releases/download/v2.1.1/GodMode9_ITA-v2.1.1.0.zip

### Developer permission

- [x] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
GodMode9 now has official translation support, to be added in the next release, so I suggest contributing to the official translation instead of forking https://crowdin.com/project/godmode9
