### ISSUE TITLE
Shut The Cam Up (Patch to remove the camera shutter sound)

### ISSUE THREAD

**Issue by TehFridge** [Universal-Team/db#149]
### Title

Shut The Cam Up

### System(s)

3DS

### Categories

Luma3DS

### Icon link

https://barachlo.szprink.xyz/4m6ATrANT19c.png

### DISCLAIMER
I do not condone any misuses of this patch for malicious purposes or whatever.

### Why tho?
Imagine you are playing your 3ds in a cafe or smt, you need to use the camera feature in some game (for example. Face Raiders) and suddenly the shutter sound bursts out of the speakers and people look at you weirdly, we wouldnt want that.

Also like... phones don't do that sort of thing (well maybe in japan, china cause there the law demands that anything with a camera has to have a shutter sound)

I mostly created this patch cause i like the vibe of vlogging with a 3ds. It has its charm you know.

### How is it possible?!
The shutter sound was embedded in some system process, we just discovered it now lol. So i just decided to null the bytes with audio data, and it worked!

### Does it work on both Old and New 3DS?
Yup. there are two seperate patches individually for the new and old model of the console.

### GitHub repository of the app

ttps://github.com/TehFridge/ShutTheCamUp/

### Author

TehFridge

### Short description

Removes the camera shutter and high-pitched beep sound from the Nintendo 3DS (works on all 3ds apps that use the camera)

### Source code link

https://github.com/TehFridge/ShutTheCamUp/

### Creation date

22nd August 2023

### Last update date

22nd August 2023

### Website link

https://github.com/TehFridge/ShutTheCamUp/

### Download page link

https://github.com/TehFridge/ShutTheCamUp/releases/

### Version number

1.0

### Version title

1.0

### Download link(s)

https://github.com/TehFridge/ShutTheCamUp/releases/download/main/new3ds.ips
https://github.com/TehFridge/ShutTheCamUp/releases/download/main/old3ds.ips

### Other notes

The patch name has to be renamed and put in a specific directory:
### For users that are below Luma3DS v13:
Both Old and New3DS: /luma/titles/0004013000001602/code.ips

### For users that are on Luma3DS v13 or higher:
Both Old and New3DS: /luma/sysmodules/0004013000001602.ips

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, just a little warning : Discord links might not work at some point, Discord specifically said that they are not an file hoster. You can publish the image on your Github repo and we'll take the link from there. I'm still adding your app in the PR for now but do consider it
