### ISSUE TITLE
Luma3DS ITA

### ISSUE THREAD

**Issue by M4nueleZ** [Universal-Team/db#151]
### Title

Luma3DS Ed. Italiana

### System(s)

3DS

### Categories

FIRM

### Image link

https://github.com/M4nueleZ/Luma3DS_ITA/raw/master/luma3dslogoita.png

### Icon link

https://github.com/M4nueleZ/Luma3DS_ITA/raw/master/luma3dslogoita.png

### Long description

Questa è l'edizione italiana di Luma3DS, un noob-proof custom firmware per console della famiglia Nintendo 3DS.

### GitHub repository of the app

https://github.com/M4nueleZ/Luma3DS_ITA

### Download link(s)

https://github.com/M4nueleZ/Luma3DS_ITA/releases/download/v13.0.2-1/Luma3DS_ITAv13.0.2-1.zip

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, please make sure your next releases are all labeled the same as the current one, just changing the version in the name

**Comment by M4nueleZ** [comment]
> Hello, please make sure your next releases are all labeled the same as the current one, just changing the version in the name of the zip file

Okay
