### ISSUE TITLE
Every copy of homebrew launcher is personalized

### ISSUE THREAD

**Issue by Alexyo21** [Universal-Team/db#152]
### Title

Pirate launcher

### System(s)

3DS

### Categories

Utility, Luma3DS

### Image link

https://github.com/Alexyo21/the-pirate-launcher/blob/master/preview.png

### Icon link

https://github.com/Alexyo21/the-pirate-launcher/blob/master/icon.png

### Long description

Refurbished build of the pirate launcher, with some new debug feature and up to date to the latest updates from official source, it doesn’t do nothing, only proves you are a pirate💀

### Screenshots

![IMG_0750](https://github.com/Universal-Team/db/assets/96795244/5f5f4faf-75ca-478a-800b-e6ae685e5fa7)

### GitHub repository of the app

https://github.com/Alexyo21/the-pirate-launcher

### Author

Alexyo21

### Short description

If you like pirating games and so on you can’t miss this opportunity.💀❄️

### Source code link

https://github.com/Alexyo21/the-pirate-launcher/tree/master

### Creation date

05/05/2023

### Last update date
21/07/2023

### Website link

https://gbatemp.net/threads/remake-unofficial-luma3ds.637949/

### Wiki link

https://gbatemp.net/threads/remake-unofficial-luma3ds.637949/

### Download page link

https://github.com/Alexyo21/the-pirate-launcher/releases/tag/news-1.0

### Version number

2.4.1

### Version title

Pirate-Launcher

### Download link(s)

https://github.com/Alexyo21/the-pirate-launcher/releases/tag/new-dev-1.0

### Other notes

If you put a note inside the sd card you will unlock some debug feature for make easier the developing of some homebrew… read on GitHub for more.
also be careful cause this will overwrite the boot.3dsx in root of your sd card 

### Developer permission

- [x] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, i'm not going to handle this in the current PR that i'm doing, you're gonna have to wait for someone else.
Reason is : i'm not sure replacing the entire 3ds folder while the 3DS is on is a good idea

**Comment by Golem642** [comment]
In every homebrewed 3DS, there's already a 3ds folder containing some useful apps and data. You specify in your releases to replace the 3ds folder with the one in your zip file.
Second of all, why can't it just be a simple .cia that you install ?

**Comment by Golem642** [comment]
You can copy the homebrew launcher and choose to change the unique ID to make a different app, or keep the same one to replace the one on your console

**Comment by Golem642** [comment]
No I'm just confused over why it's a .3dsx, because that mean you need to use the homebrew launcher to launch the pirate launcher ? Idk it's kind of weird but if it's your choice I'll put it in the db as a .3dsx

**Comment by Golem642** [comment]
Ok what i understood is : it's going to be the thing that launches for when you have "Automatically launch" set to "Homebrew Launcher" in Luma3DS settings or something like that.
I was confused because i thought you wanted it to be another Homebrew launcher app on the HOME menu, just like those crazy Wii Menu videos we see on YouTube where they have 10 different homebrew launchers
I'm just going to put a warning upon installation that this will replace the already existing homebrew boot files
