### ISSUE TITLE
Sonic Robo Blast 2 (App Request)

### ISSUE THREAD

**Issue by TwystedXYZ** [Universal-Team/db#154]
### Title

Sonic Robo Blast 2

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0xf0042

### Image link

https://github.com/derrekr/srb2_3ds/blob/master/meta/banner.bin

### Icon link

https://github.com/derrekr/srb2_3ds/blob/master/meta/icon.png

### Long description

**THIS IS FOR NEW 3DS ONLY. IT WILL NOT RUN ON OLD 3DS.**
Changelog:

HUGE performance increase thanks to mipmapping
stereoscopic 3D rendering
initial CIA support
fixed graphics glitch that was caused by uninitialized GPU shadow state registers
fixed fog color
fixed hole in GFZ2
fixed crash when DSP firmware is missing
... other miscellaneous fixes

### GitHub repository of the app

https://github.com/derrekr/srb2_3ds

### Author

derrek

### Short description

A port of Sonic Robo Blast 2 to the New 3DS.

### Download link(s)

https://github.com/derrekr/srb2_3ds/releases/download/v1.1.3/srb2_3dsv1.1.3.zip
https://github.com/mazmazz/SRB2/releases/download/SRB2_assets/SRB2-2122-assets.7z
https://github.com/mazmazz/SRB2/releases/download/SRB2_assets/SRB2-optional-assets.7z

### Other notes

n3ds only, requires srb2's files, please add them above the CIA. They come in 7Z archives, so make sure to extract.
Everything goes in sdmc:/3ds/srb2_3ds

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
@derrekr just want a confirmation that you gave permission

**Comment by derrekr** [comment]
Yes!!

**Comment by Golem642** [comment]
> Yes!!

Ok, all good then. There's been a few cases where the creator didn't give explicit permission so i felt like i needed to ask
