### ISSUE TITLE
Snes9x (updated fork)

### ISSUE THREAD

**Issue by matbo87** [Universal-Team/db#160]
### Title

Snes9x for 3DS

### System(s)

3DS

### Categories

Emulator

### Unique ID(s)

0x3849

### Icon link

https://raw.githubusercontent.com/matbo87/snes9x_3ds/master/resources/icon.png

### Long description

fork of bubble2k's **Snes9x for 3DS**, giving you more options to enjoy your SNES game collection.

### Screenshots

![dark-mode-file-menu](https://github.com/Universal-Team/db/assets/4026393/45faf47e-3916-434f-a0ca-bb978e7dce34)
![sf2-cropped-border-cover](https://github.com/Universal-Team/db/assets/4026393/f528abc8-3a8c-4014-b1d8-a3515128ade7)
![aladdin-pp-cheats](https://github.com/Universal-Team/db/assets/4026393/3bcc3a70-f251-4d77-a293-cbcffaf31833)

### GitHub repository of the app

https://github.com/matbo87/snes9x_3ds

### Author

bubble2k16 / matbo87 / willjow

### Short description

SNES9x Port for 3DS / 2DS

### Download link(s)

https://github.com/matbo87/snes9x_3ds/releases/download/v1.51.1/snes9x_3ds.cia
https://github.com/matbo87/snes9x_3ds/releases/download/v1.51.1/snes9x_3ds.3dsx

### Other notes

Related/optional assets including how to use them: https://github.com/matbo87/snes9x_3ds-assets

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, i see there's already Snes9x on the db AND another Snes9x updated for by Xeddius-Network, in order to differentiate yours how would you like it to be called exactly ?

**Comment by Golem642** [comment]
If i don't get an answer by tomorrow I'll manually set the name

**Comment by Golem642** [comment]
Well it's mainly a problem of having the same name in the db, which might cause problems in it and confusion for the people who downloads. I suggest having something like "newly updated fork" or something idk

**Comment by Golem642** [comment]
> If i don't get an answer by tomorrow I'll manually set the name

Sorry if i sounded mean, that was not my intention. I meant it like I will add your app to the db but i would set the name so nothing crashes in it and you get to change it whenever

**Comment by Golem642** [comment]
Ok so after a bit of discussion i'm going to replace the links of the udpated fork in the db by yours since the current one isn't being updated anymore

**Comment by matbo87** [comment]
> Ok so after a bit of discussion i'm going to replace the links of the udpated fork in the db by yours since the current one isn't being updated anymore

Great :) Thanks for your effort. I think this is the most convenient solution in the end.

**Comment by matbo87** [comment]
> Ok so after a bit of discussion i'm going to replace the links of the udpated fork in the db by yours since the current one isn't being updated anymore

Great :) Thanks for your effort. I think this is the most convenient solution in the end.

**Comment by matbo87** [comment]
@Golem642 @Epicpkmn11 
I have noticed that you have unfortunately used the wrong version. The correct version is actually [1.51.1](https://github.com/matbo87/snes9x_3ds/releases/tag/v1.51.1), as can be seen from the download links here.
Would it be possible to adjust this in the foreseeable future? v1.51 will crash for O3DS users.

**Comment by Epicpkmn11** [comment]
U-DB just pulls from what GitHub says is the latest, for some reason v1.51.1 isnt in the [release list](https://github.com/matbo87/snes9x_3ds/releases), if you could take a look at the release and see if there's anything weird that'd be the best fix

**Comment by matbo87** [comment]
@Epicpkmn11 thanks for your answer.

The release list looked correct as long as I was logged in with my github account, which is why I didn't notice the error myself. There are similar threads on github where users are having the same issue.

I've updated the latest release without making any changes to trigger a re-sync which solved it. 👍
