### ISSUE TITLE
new-hbmenu problem

### ISSUE THREAD

**Issue by ManiacOfGitHub** [Universal-Team/db#168]
The new release of the Homebrew Launcher (boot.3dsx) has a build that is different from the last. The builds prior provided the boot.3dsx file directly, while the latest version has it packaged within a ZIP archive named "3ds-hbmenu-2.4.2.zip"

This causes Universal Updater to fail to install the latest version of the Homebrew Launcher.

**Comment by Trickygamers** [comment]
Something similar happens with retro arch as well were it continually fails.

**Comment by Golem642** [comment]
It's because they now also includes config for libcurl ssl, and maybe more in the future. I'll modify the DB accordingly

**Comment by Golem642** [comment]
As for retroarch i'm not sure and i don't want to mess things up for the PR i'm making which has been open for way too long so i'm trying to get things done

**Comment by ManiacOfGitHub** [comment]
> As for retroarch i'm not sure and i don't want to mess things up for the PR i'm making which has been open for way too long so i'm trying to get things done

It's because RetroArch's version is now v1.16.0.2 but the latest stable release on their website still uses v1.16.0 in the URL.

**Comment by Epicpkmn11** [comment]
Fixed by #165

**Comment by Golem642** [comment]
> Fixed by #165

not for retroarch

**Comment by Epicpkmn11** [comment]
Oh, didn't see that part, it should be its own issue
