### ISSUE TITLE
sonic robo blast 2 fails to install and assets don't download right

### ISSUE THREAD

**Issue by Trickygamers** [Universal-Team/db#171]
sonic robo blast 2 cia and 3dsx both fail and the assets don't download properly

**Comment by Trickygamers** [comment]
oh and forgot to mention the obviously wrong icon being used for it needs changed. I don't know what it should be changed to but I do know something other than snes9x.

**Comment by derrekr** [comment]
srb2_3ds dev here.
Can confirm the icon is wrong. This icon should be used instead: https://github.com/derrekr/srb2_3ds/blob/master/meta/icon.png
Has anyone else tried installing srb2 and it failed?

**Comment by derrekr** [comment]
ok, seems to be failing for me as well.

**Comment by Epicpkmn11** [comment]
Fixed by d47d85637df663dcc730c7e10d57f96c4b4b392a and 520e3a83404bd96e9d6d56dd43ed2a1ce08411f7
