### ISSUE TITLE
Luma30_customluma

### ISSUE THREAD

**Issue by Peppe30brick** [Universal-Team/db#173]
### Title

Luma30_customluma

### System(s)

3DS

### Categories

FIRM, Luma3DS

### Long description

and a completely Italian luma3ds custom with new features
e una custom di luma3ds completamente italiana con delle features nuove

### GitHub repository of the app

https://github.com/Peppe30brick/Luma30

### Author

Peppe30_brick

### Short description

Custom of luma 3ds 

### Source code link

https://github.com/Peppe30brick/Luma30?search=1

### Creation date

18/11/2023

### Last update date

7 days ago 

### Website link

https://github.com/Peppe30brick/Luma30

### Download page link

https://github.com/Peppe30brick/Luma30/releases/tag/latest

### Version number

BETA2

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by lifehackerhansol** [comment]
Sorry, we will not be adding translated forks of applications; if you believe this is needed, please contact the original authors for implementation suggestions.
