### ISSUE TITLE
Citrahold

### ISSUE THREAD

**Issue by regimensocial** [Universal-Team/db#175]
### Title

Citrahold

### System(s)

3DS

### Categories

Utility, Save Tool

### Unique ID(s)

CTR-HB-CTHD (??)

### Image link

https://raw.githubusercontent.com/regimensocial/Citrahold-3DS/main/assets/banner.png

### Icon link

https://raw.githubusercontent.com/regimensocial/Citrahold-3DS/main/assets/icon.png

### Long description

Citrahold provides you with everything you need to easily move game saves from a physical 3DS to a 3DS emulator on your computer (and vice versa).

It basically allows you to cloud-sync your saves for if you like to play a game across a real 3DS and an emulator.

Please visit [the website](https://www.citrahold.com/) for much more information! It has everything you need in order to set it up.

Checkpoint (or another competent save manager) and an Internet connection are also required.

### Screenshots

https://www.citrahold.com/imagery/screenshots/1.png
https://www.citrahold.com/imagery/screenshots/2.png
https://www.citrahold.com/imagery/screenshots/3.png
https://www.citrahold.com/imagery/screenshots/4.png

### GitHub repository of the app

https://github.com/regimensocial/Citrahold-3DS/

### Author

Jamie Adams, regimensocial

### Short description

Citrahold allows you to sync saves between Citra and your 3DS.

### Website link

https://www.citrahold.com/

### Download link(s)

Latest: https://github.com/regimensocial/Citrahold-3DS/releases/latest

### Other notes

This requires a little bit of pre-setup to work, please view the guide https://www.citrahold.com/guide and/or the YouTube demonstration https://www.youtube.com/watch?v=MsqyN6I3RAM. 
Checkpoint is also required, or another competent save manager.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by regimensocial** [comment]
I wasn't sure if I was meant to generate a unique ID from somewhere, or choose one, but I boldy chose `0xFF3FE` (`000400000FF3FE00`) back when I was editing the Makefile.
Thanks

**Comment by TwystedXYZ** [comment]
well this'll be a fun new recommendation to citra users
