### ISSUE TITLE
CustomLuma3DS-ITA 

### ISSUE THREAD

**Issue by Simo3ds** [Universal-Team/db#176]
### Title

CustomLuma3DS-ITA

### System(s)

3DS

### Categories

FIRM, Luma3DS

### Long description

A Custom version of Luma3DS made by Alexyo21 and coolgamer, now Translated by Simo.

### GitHub repository of the app

https://github.com/Simo3ds/CustomLuma3DS-ITA

### Author

Simo

### Short description

Translation of CustomLuma3DS in italian

### Source code link

https://github.com/Simo3ds/CustomLuma3DS-ITA

### Creation date

23/7/23

### Last update date

9/3/2024

### Download page link

https://github.com/Simo3ds/CustomLuma3DS-ITA/releases/latest

### Version number

1.1.4-d

### Version title

1.1.4-ITA

### Download link(s)

https://github.com/Simo3ds/CustomLuma3DS-ITA/releases/download/v1.1.4-d/CustomLuma3DS-ITA-1.1.4-d.zip

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Simo3ds** [comment]
I need to update the fork, wait until put it in Unidb

**Comment by Simo3ds** [comment]
Updated

**Comment by lifehackerhansol** [comment]
Sorry, we will not be adding translated forks of applications; if you believe this is needed, please contact the original authors for implementation suggestions.

**Comment by lifehackerhansol** [comment]
As far as the issue is concerned, I was referring to [upstream Luma3DS](https://github.com/LumaTeam/Luma3DS)

We decided that we are not adding feature addition forks of Luma3DS or other applications, if such features are a necessity it should be upstreamed.
