### ISSUE TITLE
Add maintained fork of the FBI 3ds app

### ISSUE THREAD

**Issue by paulober** [Universal-Team/db#177]
### Title

FBI Enhanced

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xF8001

### Image link

https://github.com/paulober/FBI/raw/2.6.2/meta/banner.bnr

### Icon link

https://github.com/paulober/FBI/blob/2.6.2/meta/icon.icn

## FBI

FBI is an open source title manager for the 3DS.

## Features

- Browse and modify the SD card, TWL photos, TWL sounds, save data, and ext save data.
- Export, import, and erase save data from DS cartridges.
- Export, import, and delete save data secure values.
- Install titles/tickets from a file system, over a local network, or over the Internet with a URL or QR code.
  - Automatically imports title seeds on installation, either from the Internet or the SD card.
- Browse and delete pending titles (downloaded updates, in-progress eShop titles, etc).
- Customize appearance by placing replacements for RomFS resources in "sdmc:/fbi/theme/".

- Only available when run from a CIA, 3DS, or a 3DSX under Luma3DS:
  - Browse and modify CTR NAND, TWL NAND, and system save data.
  - Dump the raw NAND image to the SD card.
  - Launch titles installed to the system.

### GitHub repository of the app

https://github.com/paulober/FBI

### Author

paulober

### Short description

Open source title manager. (maintained by paulober)

### Source code link

https://github.com/paulober/FBI

### Download page link

https://github.com/paulober/FBI/releases/tag/2.6.2

### Version number

2.6.2

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by paulober** [comment]
Would this be better as image? 
https://github.com/paulober/FBI/blob/3a05c78c83a8a057f075031afea55e3e7c117ec9/meta/icon_3ds.png

**Comment by lifehackerhansol** [comment]
Sorry, we will not be accepting this submission; after verifying your source code, nothing actually changed from your application compared to the original application, going against our guidelines: <https://github.com/Universal-Team/db/blob/d437a8a8840a27ae78a039708729f5073e2dbcb3/CONTRIBUTING.md?plain=1#L13>
