### ISSUE TITLE
Change color of QR code

### ISSUE THREAD

**Issue by Yorisoft** [Universal-Team/db#179]
### Title

Change color of QR code

### System(s)

3DS

### Categories

Utility

### Long description

Please change the color of the QR code for the httpd service. The orange is hard to pick up on the 3ds camera. Had to convert it in an image editor to get it working. 

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
What httpd service ? Besides, this isn't an app request but more like a normal issue

**Comment by Golem642** [comment]
Ah i see what you mean, it might be because the latest release is a nightly. It could be possible to change this color
