### ISSUE TITLE
3DS Button Tester

### ISSUE THREAD

**Issue by TheCoolesttOne** [Universal-Team/db#180]
### Title

3DS Button Tester

### System(s)

3DS

### Categories

Utility

### GitHub repository of the app

https://github.com/TheCoolesttOne/3DS-Button-Test

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, could you please upload the icon of your app to your Github repository so that i can include it in the repo ?

**Comment by TheCoolesttOne** [comment]
sorry, i am closing this issue, as well as another one i made today. I will add the icon in a bit and open a new issue

**Comment by Golem642** [comment]
> sorry, i am closing this issue, as well as another one i made today. I will add the icon in a bit and open a new issue

Nonono, you could just add it and tell me when you're done there's no problem in that

**Comment by TheCoolesttOne** [comment]
> > sorry, i am closing this issue, as well as another one i made today. I will add the icon in a bit and open a new issue
> 
> Nonono, you could just add it and tell me when you're done there's no problem in that

oops, sorry i have opened a new one
