### ISSUE TITLE
FBI Dark Mode

### ISSUE THREAD

**Issue by xOScr** [Universal-Team/db#184]
### Title

FBI Dark Mode

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xF8001

### Icon link

https://raw.githubusercontent.com/xOScr/FBI-Dark-Mode/master/romfs/logo.png

### Long description

Dark mode open source title manager for the 3DS.

### Screenshots

![mrg_2024-02-11_21-00-38 409](https://github.com/Universal-Team/db/assets/135145676/4d4af31b-37ce-4daf-abc9-aa724035a2a3)

### GitHub repository of the app

https://github.com/xOScr/FBI-Dark-Mode

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by lifehackerhansol** [comment]
Sorry, we will not be accepting this submission; after verifying your source code, there is nothing functionally different from this app compared to the original, going against our guidelines: <https://github.com/Universal-Team/db/blob/d437a8a8840a27ae78a039708729f5073e2dbcb3/CONTRIBUTING.md?plain=1#L13>
