### ISSUE TITLE
Genesis of Dreams (2023)

### ISSUE THREAD

**Issue by WinglessPenny64** [Universal-Team/db#185]
### Title

Genesis of Dreams

### System(s)

3DS

### Categories

Game

### Unique ID(s)

000400000232C500

### Image link

https://img.itch.zone/aW1nLzEyMzYwMDUyLnBuZw==/original/UQU2%2FP.png

### Icon link

https://1drv.ms/i/s!AhzTHigwRi4BgZFE5WjyJWyFxoYRWg?e=K3ShxT

### Long description

Get ready for a new 8-bit handheld adventure!
          Genesis of Dreams!

When 2 friends, Alex and Max, slept on the job, Mech steals the mystical Elegems,
and now its trapped in the planet Genesis!

As they try to get the Elegems back, they find out that Mech also mind-controlled the rulers of North Island, the main island of planet Genesis.

Now you must help Alex and Max to stop Mech and get the Elegems back

Can you do it?

### Screenshots

![image](https://github.com/Universal-Team/db/assets/86502217/47eb5d54-f20e-4020-b6dc-97c62944fc75)
![image](https://github.com/Universal-Team/db/assets/86502217/cb8158b6-2f82-4cc5-93c2-34ff2c372c4f)
![image](https://github.com/Universal-Team/db/assets/86502217/816b3137-bd06-4452-83b3-78b0a9f83de8)
![image](https://github.com/Universal-Team/db/assets/86502217/d35ee63e-c0f2-4e1f-b2e9-d1df8b8bb215)

### Author

WinglessPenny64

### Short description

Follow Alex on his first adventure on the the Game Boy, Genesis of Dreams!

### Creation date

June 2, 2023

### Website link

https://winglesspenny64.itch.io/genesis-of-dreams

### Download page link

https://winglesspenny64.itch.io/genesis-of-dreams/download/eyJpZCI6MjEwMDIxMSwiZXhwaXJlcyI6MTcwNzc5MTEzOH0%3d.Zdhnef%2bMX0LsNzKN3Lkv4pZv1K8%3d

### Version number

v1

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hi, sorry but as of now there is no way to automatically download games from sites such as itch.io or gamejolt, this is because they require a token for every download and do not have a direct download link.
You may want to upload the CIA or 3dsx on a Github repo, which in this case we will be able to download from
See the first comments of #145 for a similar issue

**Comment by Epicpkmn11** [comment]
Sorry, but after some thought we have decided to only allow actual 3DS/DS homebrew on Universal-DB. As this is a Game Boy homebrew in a VC inject I am closing the issue.
