### ISSUE TITLE
Spirited DS

### ISSUE THREAD

**Issue by KahnerC** [Universal-Team/db#187]
### Title

Spirited DS

### System(s)

DS

### Categories

Game

### Icon link

https://img.itch.zone/aW1nLzE0MDEwNjEyLnBuZw==/315x250%23c/2LmBs3.png

### Long description

Spirited was a series about a rock star ghost who falls in love with an Australian dentist, fresh from the golden age of mad-lib television. Outside of a spartan DVD release, the series produced no merchandise...

Until now.

Today, I introduce you to Spirited DS, a barebones implementation of how I assume Top Trumps works, featuring 64x64 headshots of beloved Spirited characters, on the Nintendo DS. See how I feel these characters rate in 5 absolutely subjective qualities.

Does it fall under fair use? Who knows? But I don't think I'm causing much damage to a thirteen year old series on a sub-240p display, even if there are two of them.

The game is provided as a .nds file, suitable for a flashcart, modded 3DS, or emulator of your choice.

Tragically, there is no sound. Anyone who can help with that probably has better things to do.

Built with NightFoxLib (which feeds off of DevKitPro, LibNDS). Code was written in C++ in Notepad. Python was used to test some logic, and to process pictures from Krita.

Basic rules are: You pick one of five qualities listed on your card. If your value is bigger than your opponent's you win their card, and both cards go to the bottom of your deck. Lose, and it's your opponent's turn. They play by the same rules, and the game ends when one player has no more cards. It was primitive and dated even by late-seventies standards.

### Screenshots

https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNC5wbmc=/347x500/6j4Uac.png
https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNS5wbmc=/347x500/hHUlsQ.png
https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNi5wbmc=/347x500/abe7nq.png

### GitHub repository of the app

https://github.com/KahnerC/SpiritedDS

### Author

KahnerC

### Short description

An uninspired card game for the Nintendo DS.

### Creation date

November 2023

### Last update date

November 2023

### Website link

https://kahnerc.itch.io/spirited-ds

### Wiki link

https://kahnerc.itch.io/spirited-ds

### Download page link

https://kahnerc.itch.io/spirited-ds

### Download link(s)

https://kahnerc.itch.io/spirited-ds

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, could you provide an icon that fits the size of an actual ds icon (32*32) ? I'm going to put the current icon you provided as the banner

**Comment by KahnerC** [comment]
![icon](https://github.com/user-attachments/assets/f50188a6-edd0-4e95-9afd-fc854a6b9fef)
This should do.
![banner](https://github.com/user-attachments/assets/7d6aa29a-7ee1-40f0-9bbd-ec6a50f17342)
This would probably make a better banner.

**Comment by Golem642** [comment]
Hello, could you put both of these images in your Github repo please ? It seems that UU is unable to download them from here apparently, so having a fixed place for them would be great.

**Comment by KahnerC** [comment]
They're in the repository now.
