### ISSUE TITLE
Please add Checkpoint

### ISSUE THREAD

**Issue by sthetix** [Universal-Team/db#19]
Checkpoint

**System(s)**

Game saves manager

**Image link**

**Icon link**

**Long description**

**Screeshots**

**GitHub repository of the app**

FlagBrew

**Short description**

https://github.com/FlagBrew/Checkpoint/archive/refs/tags/v3.7.4.zip

Oct 1, 2017

Dec 9, 2019

https://github.com/FlagBrew/Checkpoint/releases

https://github.com/FlagBrew/Checkpoint

https://github.com/FlagBrew/Checkpoint/releases/tag/v3.7.4

Checkpoint 3.7.4

Checkpoint 3.7.4

Dec 9, 2019

**Download link(s)**

- [ ] I am the app developer or have permission from the app developer to make this request

**Comment by SuperSaiyajinStackZ** [comment]
See here for reasons, why Checkpoint hasn't been added to Universal-DB: https://github.com/Universal-Team/db/issues/13.

**Comment by sthetix** [comment]
Thanks a bunch.
