### ISSUE TITLE
Quiznos Employee Training Software DX

### ISSUE THREAD

**Issue by joey5802** [Universal-Team/db#192]
### Title

Quiznos Employee Training Software DX

### System(s)

3DS

### Categories

Game, Emulator

### Long description

Quiznos Employee Training Software DX is a homebrew Game Boy Color game where the player assumes the role of a Quiznos Employee-in-Training. Complete numerous zany missions and tasks with the goal of collecting as many peppers as possible by the end to make Uncle Quizno proud.

### Download link(s)

https://github.com/joey5802/quiznosDX/raw/main/QuiznosEmployeeTrainingGameDX.cia

### Other notes

This is simply my Game Boy game inside of a GB Virtual Console app.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, can you provide an icon for the app please ?

**Comment by Epicpkmn11** [comment]
Sorry, but after some thought we have decided to only allow actual 3DS/DS homebrew on Universal-DB. As this is a Game Boy homebrew in a VC inject I am closing the issue.
