### ISSUE TITLE
sleep exit

### ISSUE THREAD

**Issue by makaroonie** [Universal-Team/db#199]
when i used sleep exit (not *completely* knowing what it was) i found my custom light staying on for the duration of me using my 3ds and id like to remove the sleep exit light but im not sure how or if it’s even possible

update: i fixed it myself by changing the pattern

**Comment by Golem642** [comment]
this issue was probably intended for https://github.com/Golem642/CtrRGBPAT2 so next time you have an issue with CtrRGBPAT2 come send it there, universal team probably won't be helping you with this.
i should really publish the next update lmao
