### ISSUE TITLE
3DS vJoy Controller

### ISSUE THREAD

**Issue by memeToasty** [Universal-Team/db#202]
### Title

3DS vJoy Controller

### System(s)

3DS, DS

### Categories

Utility

### Long description

With this, you can use one or more 3DS consoles as a single, coherent controller on your PC.

Useful if u need a button box or something like that.

Visit the [repo](https://github.com/StringJan/3ds-vJoy-controller) for more info on how to use it.

### GitHub repository of the app

https://github.com/StringJan/3ds-vJoy-controller

### Author

memeToasty, StringJan

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, could you provide the icon of your 3dsx please ? Or do you not have one ?

**Comment by memeToasty** [comment]
For this app, I actually do not have one. Is it required?

**Comment by Golem642** [comment]
No it isn't, but it would look better/differentiate you from the other apps on the UU. I'm gonna put it as is

**Comment by memeToasty** [comment]
Thank you very much
