### ISSUE TITLE
3DWEB

### ISSUE THREAD

**Issue by WLHQ** [Universal-Team/db#206]
### Title

3DWEB

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0x7548

### Image link

https://github.com/WLHQ/3DWEB/blob/main/resources/banner.png

### Icon link

https://github.com/WLHQ/3DWEB/blob/main/resources/icon.png

### Long description

A flexible web server that can handle sd card file reads, crypto operations, system requests and raw memory operations.

### GitHub repository of the app

https://github.com/WLHQ/3DWEB

### Author

WLHQ

### Short description

A web server made in C for the 3DS.

### Source code link

https://github.com/WLHQ/3DWEB

### Creation date

April, 25, 2024

### Last update date

April, 25, 2024

### Download page link

https://github.com/WLHQ/3DWEB/releases

### Version number

v1.0.0

### Version title

Initial release 

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by WLHQ** [comment]
Will this automatically update in universal updater? I just released a new version of this.

**Comment by dimaguy** [comment]
I can't see a difference to this from the one I published in the shop, can someone enlighten me?
The MIT license in the code also disregards my contributions(to be fair now that I checked I forgot to include my name in mine) and the ones of the person before

**Comment by WLHQ** [comment]
Dimaguy it's a slightly modified version of what you previously had on your repo about 2 years ago that makes the user experience slightly more intuitive. There are plans for MIME types for the software to support but I haven't got any success yet with that in my own testing & scrapped previous attempts at that. And for the licensing, yeah that went over my head on that, my apologies on that one.

3DWEB is derivative of 3ds-httpd, I have implemented C code that makes a new directory called "Websites" and within that directory a file "index.html" is created. Nothing else is written to the sd card upon startup from the software itself. Also the hardcoded html response includes an internal link to that html page within "/sdcard/Websites/index.html". 

I understand your concerns about the software and I don't have any bad intentions. I was just trying to see what I could do to improve the project and as previously stated, I didn't get too far, yet.

**Comment by dimaguy** [comment]
> Dimaguy it's a slightly modified version of what you previously had on your repo about 2 years ago that makes the user experience slightly more intuitive. There are plans for MIME types for the software to support but I haven't got any success yet with that in my own testing & scrapped previous attempts at that. And for the licensing, yeah that went over my head on that, my apologies on that one.
> 
> 3DWEB is derivative of 3ds-httpd, I have implemented C code that makes a new directory called "Websites" and within that directory a file "index.html" is created. Nothing else is written to the sd card upon startup from the software itself. Also the hardcoded html response includes an internal link to that html page within "/sdcard/Websites/index.html". 
> 
> I understand your concerns about the software and I don't have any bad intentions. I was just trying to see what I could do to improve the project and as previously stated, I didn't get too far, yet.

That is fine, but you could have made a PR instead? I haven't reviewed the code because I need a more concise diff but that does sound like something I could accept.
Furthermore I could even make you a mantainer with write access if no issues arise

**Comment by WLHQ** [comment]
Yeah I could've pull requested but I evidently didn't. That's something past me probably knows & I honestly don't remember why I didn't do that in the first place.

**Comment by dimaguy** [comment]
> Yeah I could've pull requested but I evidently didn't. That's something past me probably knows & I honestly don't remember why I didn't do that in the first place. 

PRs are welcome! Feel free to open one whem you want and Ill take a better look as soon as possible
