### ISSUE TITLE
fnaf 1 by fredev

### ISSUE THREAD

**Issue by gannon182** [Universal-Team/db#21]
**Name of t

**System(s)**

**Categories**

**Image link**

**Icon link**

**Long description**

**Screeshots**

**GitHub repository of the app**

**Author**

**Short description**

**Source code link**none

**Creation date**RELEASED ON 1/26/2021

**Last update date**RELEASED ON 1/26/2021

**Website link**https://gamejolt.com/games/fnaf13dsremastered/576273

**Wiki link**

**Download page link**https://gamejolt.com/games/fnaf13dsremastered/576273

**Version number**0.3.1-pre1

**Version title**

**Last update date**1/26/2021

**Download link(s)** https://gamejolt.com/games/fnaf13dsremastered/576273

- [x] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Is there a download for this on GitHub or so? Game Jolt doesn't appear to have a permalink to the file that Universal-Updater would be able to download... It seems to need you to go to the page, wait a few seconds then it downloads with JavaScript...

**Comment by Epicpkmn11** [comment]
Oh sorry for the late reply, I can still add it to the website, it just can't be downloaded from Universal-Updater without a direct like, so if it could be hosted somewhere with a direct download that'd work better fyi

**Comment by Epicpkmn11** [comment]
Oh, just noticed the QR code links to Dropbox, so I should be able use that download link and it'll work in Universal-Updater. GitHub is still the ideal place though fyi as we can automatically check updates and such from GitHub
