### ISSUE TITLE
Trogdor: Reburninated download fails in app due to different content name

### ISSUE THREAD

**Issue by Mode8fx** [Universal-Team/db#211]
Previous versions of Trogdor: Reburninated were released as a ZIP archive containing a folder, with both the ZIP and folder named `Trogdor-Reburninated-vX.XX-3ds`, where `X.XX` is the version number. For the latest version; this has changed. The ZIP is still named `Trogdor-Reburninated-v2.2-3ds.zip`, but the contained folder is simply `Trogdor-Reburninated-3ds`. This also applies to the CIA build, just with `-cia` at the end.

I don't know if it's currently configured to match whatever the latest version number is, or if it was hardcoded to use an older version, but please change the contained folder to not include a version number. Thanks!

**Comment by lifehackerhansol** [comment]
Should be fixed by f969686c609e48031c5873969b508ba03db817e3
