### ISSUE TITLE
Anemone 3DS ESP

### ISSUE THREAD

**Issue by Tristanabs** [Universal-Team/db#213]
### Title

Anemone 3DS ESP

### System(s)

3DS

### Categories

Utility

### Image link

https://media.discordapp.net/attachments/1231978722391887882/1239168250634440815/anemone_3ds.png?ex=6641f0dd&is=66409f5d&hm=38c80ef9a9cab07aac00989c31e4d2232f24a6309f0b666c99912842fa6c440e&=&format=webp&quality=lossless

### Icon link

https://media.discordapp.net/attachments/1231978722391887882/1239210969914146837/icon.png?ex=664218a6&is=6640c726&hm=a82e97e81d89e2ae894bef32523c4c4c384dc016bff5fbdd1adf448e25ee69c2&=&format=webp&quality=lossless

### Long description

Anemone 3ds ESP is a copy of Anemone 3DS but in Spanish (it is 90% finished)

### GitHub repository of the app

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP

### Author

Saturn team 3DS scene, Felix 64

### Short description

Anemone 3DS pero en Español

### Source code link

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP.git

### Creation date

12/05/2024

### Last update date

12/05/2024

### Download page link

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP/releases/tag/v1.0

### Version number

v 1.0

### Version title

v 1.0

### Download link(s)

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP/releases/tag/v1.0

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by lifehackerhansol** [comment]
Sorry, we will not be adding translated forks of applications; if you believe this is needed, please contact the original authors for implementation suggestions.
