### ISSUE TITLE
YouTube 

### ISSUE THREAD

**Issue by Ryu-524** [Universal-Team/db#214]
### Title

YouTube

### System(s)

3DS, DS

### Categories

Utility

### Image link

www.youtube.com

### Icon link

www.youtube.com

### GitHub repository of the app

I don't know

### Author

Aaaaaa

### Short description

デスクトップです

### Source code link

www.youtube.com

### Creation date

2024 5/14

### Last update date

10.1

### Website link

www.youtube.com

### Wiki link

www.youtube. com

### Download page link

www.youtube.com

### Version number

10.1

### Version title

1.1

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Ryu-524** [comment]
Can you deliver it today or tomorrow?

**Comment by Ryu-524** [comment]
YouTube app

**Comment by NightScript370** [comment]
This isn't a spot to request apps to be made. This is to request apps that are already made to be put up on our store
