### ISSUE TITLE
Luma3DS in French

### ISSUE THREAD

**Issue by TheRinzler65** [Universal-Team/db#219]
### Title

Luma3DS en Français

### System(s)

3DS

### Categories

FIRM, Luma3DS

### Image link

https://github.com/TheRinzler65/Luma3DS-French/blob/master/logoluma3dsfr.png

### Icon link

https://github.com/TheRinzler65/Luma3DS-French/blob/master/logoluma3dsfr.png

### Screenshots

- Correction d'un bug où l'option de connexion sans fil remplaçait l'option de volume
- Forcer le menu wifi : gérer correctement les emplacements wifi non configurés
- Modifications mineures du chargeur de plugin

---

**Journal des modifications de la v13.1 :**

- Ajoute d'un remplacement du curseur de volume :
 - Actuellement, cette option se trouve sous « Configuration du système » dans le menu Rosalina et enregistre automatiquement, tout en étant sous [misc] dans config.ini. En effet, cette option n'est prise en charge que pour NATIVE_FIRM. Cela pourrait changer à l'avenir.
- Lors de l'utilisation de cette option, l'arrêt de la console peut parfois prendre plus de temps
- Ajoutez une entrée explicite "Boot chainloader", au-dessus de "Save and exit" dans le menu de configuration de démarrage
- Supprimer l'option "Autoriser les combos "Allow Left+Right / Up+Down combos for DSi" inutilisée et inutile
- Masquer l'option "Activer les filtres de mise à l'échelle personnalisés pour DSi"
- Correction d'un problème où le "screeninit baremetal" entraînait deux écrans blancs ou des couleurs incorrectes, généralement lors du lancement des charges utiles Arm9
- Rosalina : afficher le SSID dans le menu "Force wifi connection"
- LayeredFS : amélioration de la détection du point de montage RomFS de la mise à jour du jeu
- D'autres améliorations de la stabilité globale du système et d'autres ajustements mineurs ont été apportés pour améliorer l'expérience utilisateur

De plus, avec nos remerciements à https://github.com/devkitPro, cette version de Luma3DS est livrée avec la version 2.4.3 du - Homebrew Menu , lui-même fourni config/ssl/cacert.pem pour une utilisation avec libcurl.

### GitHub repository of the app

https://github.com/TheRinzler65/Luma3DS-French

### Author

Rinzler

### Short description

"Custom Firmware" pour Nintendo 3DS

### Source code link

https://github.com/TheRinzler65/Luma3DS-French/releases

### Creation date

26/05/2024

### Download page link

https://github.com/TheRinzler65/Luma3DS-French/releases/download/v13.1.1/Luma3DSV13.1.1_FR.zip

### Version number

13.1.1

### Version title

v13.1.1

### Download link(s)

https://github.com/TheRinzler65/Luma3DS-French/releases/download/v13.1.1/Luma3DSV13.1.1_FR.zip

### Other notes

Je ne sais pas si cela doit être dit mais cela ne marche pas sur le mod CTGP-7 à cause de "l'Anti-Cheat", cela va faire une erreur "Unknown Luma3DS build" car tout simplement c'est pour éviter les triches, etc.

I don't know if this needs to be said, but it doesn't work on the CTGP-7 mod because of the “Anti-Cheat”, it will give an “Unknown Luma3DS build” error, simply to avoid cheats, etc.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by TheRinzler65** [comment]
hello I would like to know if it can be added ^^

**Comment by Epicpkmn11** [comment]
Closed by 57cb9c6c52807529a94be234f68633248b998879
