### ISSUE TITLE
Celeste Classic port for 3DS

### ISSUE THREAD

**Issue by MateoThePro** [Universal-Team/db#22]
**Celeste Classic**

**3DS**

**Port, Celeste, VC, Homebrew**

****

**https://github.com/MateoThePro/Celeste-Classic-3DS/blob/main/celeste_classic_3ds_icon.png**

**Celeste Classic ported from gba. GBA Port made by LinuxCat, Celeste classic made by Matt Makes Games.**

**https://github.com/MateoThePro/Celeste-Classic-3DS/blob/main/celeste_classic_3DS_screenshot.png**

**https://github.com/MateoThePro/Celeste-Classic-3DS**

**MateoThePro**

**Celeste Classic port by MateoThePro, gba port by LinuxCat, Celeste Classic made by Matt Makes Games**

**Source code link**

**16.4.2021.**

**16.4.2021.**

**Website link**

**https://celestegame.fandom.com/wiki/Celeste_Classic**

**Download page link**

**1.0**

**Version title**

**16.4.2021.**

**https://github.com/MateoThePro/Celeste-Classic-3DS/blob/main/CelesteClassic_v1_1_homebrew.cia**

- [X (I am not the developer)] I am the app developer or have permission from the app developer to make this request

**Comment by MateoThePro** [comment]
If you need to quickly contact me go on Discord and DM me, my username: MateoThePro#4422

**Comment by Epicpkmn11** [comment]
Is this on GitHub or so? I don't think zippyshare will work with Universal-Updater as it makes you wait for ads and such.

**Comment by MateoThePro** [comment]
> Is this on GitHub or so? I don't think zippyshare will work with Universal-Updater as it makes you wait for ads and such.
> 
> (GitHub repository releases work best for Universal-DB as we're able to automatically gather most of the metadata)

Ok, I will make a Github page.

**Comment by Epicpkmn11** [comment]
FYI when using the GPL-3 license you are required to provide source code. If you don't have / can't share the source I'd recommend changing the license on that repository

**Comment by MateoThePro** [comment]
Ok, I will remove the licence but I can't do it right now because GitHub if
frocking with me.

ned, 18. tra 2021. 00:57 Pk11 ***@***.***> je napisao:

**Comment by Epicpkmn11** [comment]
One more thing, especially if there are going to be updates to this I would recommend making a [release](https://github.com/MateoThePro/Celeste-Classic-3DS/releases) instead of just uploading the files to the repository as version numbers, downloads, update notes, etc can all be automatically gathered from the releases where they need to be manually specified for repository downloads.

How it is now is fine though, especially if there won't be updates.

**Comment by MateoThePro** [comment]
I won't make any updates. And thanks for the license tip.

ned, 18. tra 2021. 01:10 Pk11 ***@***.***> je napisao:

**Comment by MateoThePro** [comment]
You guys put the wrong icon picture, the icon is on the GitHub page and isn't my profile picture.

**Comment by SuperSaiyajinStackZ** [comment]
The icon should be 48x48.
