### ISSUE TITLE
Add Anemone ESP 

### ISSUE THREAD

**Issue by Tristanabs** [Universal-Team/db#222]
### Title

Anemone 3DS ESP

### System(s)

3DS

### Categories

Utility

### Icon link
![icon](https://github.com/Universal-Team/db/assets/76444200/e1abd256-9b86-4c1b-bfe6-a6684c0b5df2)

### Long description

Anemone 3DS translated into Spanish, there is both the translation file and the .cia and .3dsx, I also opened a PR for the Original Anemone so that if you want you can add it.

### Screenshots

![2018-01-09_16-04-23 476_sup](https://github.com/Universal-Team/db/assets/76444200/a29acda1-dade-4521-a16d-41e620f1ed22)

![2018-01-09_16-04-36 862_sup](https://github.com/Universal-Team/db/assets/76444200/6

![2018-01-09_16-04-47 640_inf](https://github.com/Universal-Team/db/assets/76444200/b10bd1c8-5b98-4e3b-9eaa-f6ba991b1ce5)
1f8ebed-cd04-45b6-b675-d0780a9232a7)

### GitHub repository of the app

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP

### Author

Saturn Team, Felix 64

### Short description

Anemone 3DS pero en Español

### Source code link

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP.git

### Creation date

12/05/2024

### Last update date

31/05/2024

### Download page link

https://github.com/Saturn-Team-3DS-Scene/AnemoneESP/releases/tag/V1.1

### Version number

v 1.1

### Version title

Anemone 3DS ESP 1.1

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by NightScript370** [comment]
It is now merged into the main Anemone. Thereby, this can be closed
