### ISSUE TITLE
Five Nights at Freddy's 1 3ds

### ISSUE THREAD

**Issue by PlexerThomas** [Universal-Team/db#229]
### Title

Fnaf 1

### System(s)

3DS

### Categories

Game

### Long description

A remaster of the original Fnaf 1 3ds.

This game is a remake of fnaf 1 for the 3ds, and works very well. Steady 30-60 fps all time, and this game is still being worked on according to the creator, but he mentioned this in 2021. Its like the fnaf 1 you play on pc or your phone etc, but a few addons like Golden freddy that are not added yet.

### Screenshots

![afbeelding_2024-06-24_192321906](https://github.com/Universal-Team/db/assets/173718095/4d0cb3dd-3671-4b61-847a-deab8ca8d195)
![afbeelding_2024-06-24_192339848](https://github.com/Universal-Team/db/assets/173718095/4042e1b3-bce3-4878-b059-840853222cdd)
![afbeelding_2024-06-24_192410468](https://github.com/Universal-Team/db/assets/173718095/bdacb59d-3115-425c-8a95-77f6a3b823c8)
video: https://youtu.be/ZkqFLwlFm8w

### GitHub repository of the app

https://github.com/BasHeemskerk/FNaF-1-3DS

### Author

BasDEV

### Short description

Fnaf 1 on 3ds

### Source code link

https://github.com/BasHeemskerk/FNaF-1-3DS

### Creation date

1/17/2021

### Last update date

1/26/2021

### Website link

https://gamejolt.com/games/fnaf13dsremastered/576273

### Wiki link

https://gamejolt.com/games/fnaf13dsremastered/576273

### Download page link

https://dlhb.gamebrew.org/3dshomebrews/five_nights_at_freddys_1_3ds_remastered.zip

### Version number

0.3.1-pre1

### Version title

fnaf-1-remastered-0.3.1-pre1

### Download link(s)

https://dlhb.gamebrew.org/3dshomebrews/five_nights_at_freddys_1_3ds_remastered.zip

### Other notes

I have never added a game to github ever, so if I did a bad job at this, I am sorry.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by tobid7** [comment]
As the Game is made with Unity it cannot be added to Universal-DB. See Universal-DB guidelines Rule 1!
