### ISSUE TITLE
Halo solitude renewed has no zip

### ISSUE THREAD

**Issue by Trickiy** [Universal-Team/db#244]
On the site the zip file can be downloaded but not on the 3ds.

**Comment by Epicpkmn11** [comment]
I never show zip downloads in Universal-Updater except in unusual circumstances. It should have options for CIA and 3DSX which each automatically download the zip content too, no?

I didn't test so it may be bugged

**Comment by Trickiy** [comment]
Oh this is just be being a idiot situation lol its not bugged it works as intended.
