### ISSUE TITLE
Add secret code to OFF's update notes or something

### ISSUE THREAD

**Issue by Trickiy** [Universal-Team/db#245]
I have been playing OFF and just got to a point were the only way to proceed is by a secret code found in the readme file. Please add the following code somewhere "Down - Left - Up - Right - Z - J - B - D - B - Start". This took me hours to realize till after watching part of Markipliers playthrough.

**Comment by lifehackerhansol** [comment]
This appears to be an upstream issue, please head there: https://github.com/fauxfennec/OFF3DS
