### ISSUE TITLE
TJAPlayer for 3DS

### ISSUE THREAD

**Issue by LuMariGames** [Universal-Team/db#246]
### Title

TJAPlayer for 3DS

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0xB7655

### Image link

https://raw.githubusercontent.com/LuMariGames/TJAP_3DS/main/resource/icon.png

### Long description

TJAPlayer for 3DSを約2年ぶりにTogeToge公認の上、更新しました。

### Screenshots

![](https://github.com/user-attachments/assets/f2c06b3d-5130-48aa-b820-358499870caa)
![](https://github.com/user-attachments/assets/7af5814a-87b3-46fa-b27c-003bb4eb2882)

### GitHub repository of the app

https://github.com/LuMariGames/TJAP_3DS

### Author

MarioGames

### Short description

TJAPlayer for 3DS - Music game of the TJA file.

### Creation date

2024-07-29

### Last update date

2024-07-29

### Version number

1

### Version title

v1.3.11

### Download link(s)

TJAP_3DS.cia: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.11/TJAP_3DS.cia
TJAP_3DS.3dsx: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.11/TJAP_3DS.3dsx

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, it seems this is a blatant copy of https://github.com/togetg/TJAPlayer_for_3DS which is already present in the universal updater. If this is actually a fork, please provide the changes you've made in which case we might be able to replace the app on the db with yours

**Comment by LuMariGames** [comment]
(I'll say it in advance, but I'm not good at English, so I'm using Google Translate.)

I made three main changes and added elements.

1. Implementation of Taiko Tower and Rank Dojo

Taiko Tower is one of the elements of "Wakuwaku Adventure Land" in the PS2 software "Taiko no Tatsujin Dokka! to Omori Nanadaime",
and is a mode in which you clear a song without making a specific number of failed attempts.

In the case of this software, enter the number 5 into the string "COURSE:" in the .tja file,
and write the variable "LIFE:".

Then enter any value (a number that allows you to make a failed attempt) into the variable name (LIFE:) you wrote earlier, save it,
and use FTPD or similar to put it in the tjafiles folder on the SD (or MicroSD) card.

After that, when you start it up, find the .tja file you put in earlier and run it to play Taiko Tower.

And the Dan-I Dojo has a similar system to the AC (arcade version),
where you clear three songs while completing up to three conditions.
I created a Wiki (*1)
for information on how to create a Dan-I Dojo using a .tja file, so
you can see that.
Once you've created it, put it on an SD (MicroSD) card as before,
search for the corresponding .tja file, and run it.

2. Adding some options
After loading, the bottom screen has performance options,
which are divided into several pages.
The third page has two new options.

The first is the repeat speed.
The repeat speed sets how many frames the repeat notes and balloon notes are hit in AUTO mode.
So, for example, if you set it to 1, AUTO will hit 60 times per second when repeating.
(Setting it to 0 will stop repeating at all.)

The second is speed (fixed).
When this is ON, the speed change caused by the "#SCROLL" command will be fixed.
Conversely, when it is OFF, the speed change caused by the "#SCROLL" command will be added.

3. Some bugs fixed
Some of the bugs fixed are:
- Fixed a crash when specifying x4 or more in the speed option
- Fixed the start point shifting when the speed change caused by "#SCROLL"
- Fixed the number of hits of the balloon not matching when specifying a potato note
These are the three bugs.

4. Final words
This software is released as the successor to TJAPlayer for 3DS created by TogeToge.
And it is being created with TogeToge's official approval.

Lastly, I would like to make a correction to this software request, so I will write it here.
The reason is that the software in the download link is old.

Long description
TJAPlayer for 3DSを約2年ぶりにTogeToge公認の上、更新しました。
This software is produced under the official authorization of TogeToge.

・太鼓タワーと段位道場の実装
・一部オプションの追加
・その他一部の不具合修正

・Implementation of Taiko Tower and Rank Dojo
・Addition of some options
・FIXES OF OTHER FAILURE

Author
MarioGames&TogeToge

Last update date
2024-8-10

Version title
v1.3.12(A)

Download link(s)
TJAP_3DS.3dsx: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.12(A)/TJAP_3DS.3dsx
TJAP_3DS.cia: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.12(A)/TJAP_3DS.cia

**Comment by Golem642** [comment]
Okay, thank you for your answer. I'm going to replace the old version with this fork then
