### ISSUE TITLE
Ib port

### ISSUE THREAD

**Issue by Teruniii** [Universal-Team/db#247]
### Title

Ib

### System(s)

3DS, DS

### Categories

Game

### Image link

https://static.wikia.nocookie.net/ibgame/images/6/69/Chara_ib.png/revision/latest?cb=20170914175546

### Icon link

https://static.wikia.nocookie.net/ibgame/images/3/3e/Ib_top_01.jpg/revision/latest?cb=20121029045535

### Long description

https://vgperson.com/games/ib.htm

### Screenshots

![](https://66.media.tumblr.com/080e453336eab017b3cda0d03b395227/tumblr_o43sxr0OCM1ubn7fro1_1280.gif)

### Author

Kouri

### Short description

A young girl named Ib visits an art gallery with her parents. While perusing the various works of art, Ib suddenly realizes that she is alone. ..

### Other notes

Im sorry if i didnt add the correct description but i hope their could be new rpg maker ports soon

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by lifehackerhansol** [comment]
This app doesn't appear to actually exist.
