### ISSUE TITLE
Earthbound Ultimate 3DS

### ISSUE THREAD

**Issue by IceEnderman** [Universal-Team/db#256]
### Title

Earthbound Ultimate 3DS

### System(s)

3DS

### Categories

Game

### Image link

file:///C:/Users/Rachael/Desktop/Lucas's%20Cool%20Stuff/Jeff.png

### Icon link

file:///C:/Users/Rachael/Desktop/Lucas's%20Cool%20Stuff/Jeff.png

### Long description

The Ultimate Version of Earthbound!
WORKS ON OLD 3DS/2DS SYSTEMS (DESPITE BEING A SNES GAME)
This is a 3DS port of an Earthbound hack that I made.

### GitHub repository of the app

https://github.com/IceEnderman/eb-ultimate

### Author

Lucas ''Ice Enderman'' Dowling

### Short description

The Ultimate Earthbound Experience now on 3DS!

### Website link

bit.ly/eb-ultimate

### Download page link

file:///C:/Users/Rachael/Desktop/EB-Ultimate-3DS/EB-Ultimate.cia

### Download link(s)

https://gamebanana.com/mods/527416
https://gamejolt.com/games/eb-ultimate/911141

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, the images link you sent are link from your computer which i cannot access.
Furthermore, it seems this contains copyrighted content in which case the standalone cia app/gba game cannot enter this Unistore as per rule 1 of the [contributing guidelines](https://github.com/Universal-Team/db/blob/master/CONTRIBUTING.md).
I see however that you included an ips patch for the original game, this could maybe do the work but it has to be specified that the rom hack needs to be applied at every game launch
Do you still want this to be included ?
