### ISSUE TITLE
Introducing YouTube 2.0

### ISSUE THREAD

**Issue by Kikiprogamer457** [Universal-Team/db#265]
### Title

NSMBS

### System(s)

3DS

### Categories

Game

### Long description

---
author: Kikiprogamer457
avatar: https://avatars.githubusercontent.com/u/180136550?v=4
categories:
- utility
color: '#e81314'
color_bg: '#c70406'
created: '2024-09-02'
description: A Homebrew YouTube Client For The 3Ds!
download_page: https://github.com/Kikiprogamer457/YouTube2.0/releases
downloads:
  YouTube 2.3dsx:
    size: 6052304
    size_str: 5 MiB
    url: https://github.com/Kikiprogamer457/YouTube2.0/releases/download/v0.5.0/YouTube2.3dsx
  YouTube 2.0.cia:
    size: 4314048
    size_str: 4 MiB
    url: https://github.com/windows-server-2003/ThirdTube/releases/download/v0.5.4/ThirdTube.cia
github: Kikiprogamer457/YouTube 2.0
icon: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQUfDX_AsFxMY29FjnvC0hWhoQLwjxV6-KLrI_pBt83uM8LENru
image: https://static1.anpoimages.com/wordpress/wp-content/uploads/2020/10/07/YouTubeOutlineIconHero-01.png?q=50&fit=crop&w=1100&h=618&dpr=1.5
image_length: 9933
layout: app
license: gpl-3.0
license_name: GNU General Public License v3.0
qr:
  YouTube 2.0.cia: https://db.universal-team.net/assets/images/qr/YouTube2.0-cia.png
screenshots:
- description: Comments
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/comments.png
- description: General
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/general.png
- description: Search
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/search.png
source: https://github.com/Kikiprogamer457/YouTube2.0
stars: 208
systems:
- 3DS
title: ThirdTube
unique_ids:
- '0xBF74D'
update_notes: '<p dir="auto">This is a minor fix regarding page loading issues.</p>

  <ul dir="auto">

  <li>Fixed channel page not loading</li>

  <li>Fixed like count not showing up on video page</li>

  <li>Replaced Home with Trending, since YouTube started to require tracking data(and
  at least one search/video watching with the tracking id) for Home</li>

  </ul>

  <p dir="auto"><strong>Note : the binary has been updated at 2024-03-08 9:16 UTC
  for a fix. Please download it again if you downloaded the binary before this</strong></p>'
updated: '2024-03-08T09:05:14Z'
version: v0.5.4
version_title: v0.5.4
website: https://gbatemp.net/threads/release-thirdtube-a-homebrew-youtube-client-for-the-new-3ds.591696/
---

### Screenshots

screenshots:
- description: Comments
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/comments.png
- description: General
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/general.png
- description: Search
  url: https://db.universal-team.net/assets/images/screenshots/thirdtube/search.png
source: https://github.com/Kikiprogamer457/YouTube2.0

### Author

Kikiprogamer457

### Short description

A Homebrew YouTube Client For The 3Ds!

### Creation date

2024-09-02

### Last update date

2024-09-02

### Version number

0.5.0

### Version title

v0.5.0

### Download link(s)

https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/releases/download/v1.7.1.0-beta/MarioVsLuigi-Win64-v1.7.1.0-beta.zip

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by MisterSheeple** [comment]
The GitHub links don't seem to go anywhere. Even then, it seems like this is just ThirdTube, which already exists on Universal-DB.
