### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Gugish** [Universal-Team/db#266]
### Title

hi

### System(s)

DS

### Categories

Game, Emulator, Utility, Save Tool

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
empty template
