### ISSUE TITLE
get it done

### ISSUE THREAD

**Issue by 25adschwartz** [Universal-Team/db#27]
**BrowserQuest**

**PC**

**Categories**

**Image link**

**Icon link**

**Long description**

**Screeshots**

**GitHub repository of the app**

**Author**

**Short description**

**https://browserquest2.rastergames.com/**

**?**

**?**

**https://browserquest2.rastergames.com/**

**Wiki link**

**?**

**Version number**

**Version title**

**Last update date**

**Download link(s)**

- [ ] I am the app developer or have permission from the app developer to make this request

**Comment by SuperSaiyajinStackZ** [comment]
Only `3DS` and `NDS` Requests are valid. Closing.
