### ISSUE TITLE
FourthTube

### ISSUE THREAD

**Issue by erievs** [Universal-Team/db#271]
### Title

FourthTube

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0xBF74D

### Image link

https://github.com/erievs/FourthTube/blob/main/resource/banner.png?raw=true

### Icon link

https://github.com/erievs/FourthTube/blob/main/resource/icon.png?raw=true

### Long description

FourthTube is a fork of ThirdTube which fixes video playback and is activity maintained by multiple people. They're plans to add dislikes and other features not present in ThirdTube.

### Screenshots

![8kH3O5J(1)](https://github.com/user-attachments/assets/3620bbab-4f98-4df0-994d-b1c1d8852b03)

### GitHub repository of the app

https://github.com/erievs/FourthTube

### Author

NCP3.0,5GBurrito,Smu1zel,WindowsServer2003 and 2B_enpitsu

### Short description

Another work-in-progress fork of the homebrew YouTube client for the 3DS called ThirdTube

### Source code link

(https://github.com/erievs/FourthTube/archive/refs/heads/main.zip)

### Creation date

8/9/2024 (DMYYYY)

### Last update date

12/9/2024 (DMYYYY)

### Website link

None

### Wiki link

None

### Download page link

[_No response_](https://github.com/erievs/FourthTube/tags)

### Version number

Beta 13.1 or b13.1

### Version title

Fixes!

### Download link(s)

https://github.com/erievs/FourthTube/raw/main/FourthTube.cia

### Other notes

This probably would be better tagged as an app rather than a util. 

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by 5GBurrito** [comment]
hello, i helped on the project, i would like to specify that this is a **working** youtube client on the 3ds built off of thirdtube
