### ISSUE TITLE
Dinosaur Game 3DS

### ISSUE THREAD

**Issue by Kirbylikeshomebrew** [Universal-Team/db#282]
### Title

Dinosaur Game 3DS

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0004000000A1B200

### Image link

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARwAAACxCAMAAAAh3/JWAAAAulBMVEUAAAAtLS2fn6AcW4ZsbWxLTUtCRUP4/v8XWYU4bJIAU4EDVYKnqavG1+Nsbm/k5+qEo7sICQgATn7u9vxRUlJ4eHkZGhk/QD9eX1+CgoJgY2GyxtUVFRW7zdrv9PjX5O6Ojo+Wlpe/wcK0t7nGy87P1NYgIyGfp6pCSE3b3+FJTEmnt8F1f4WDh4k2OTicoJ1qc3k1PUJKeJpqi6aNqL1fh6V0lrBRfJ2dtskoY4xkiqZXV1kzNTQmKCbHY3dbAAADU0lEQVR4nO3ba3eiVhiG4e0RIiggoCh4QBOtNkPbzIQZo/n/f6ugoKiYSbu6CpPc1ycXbPTN4z5ABCEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfEzG1HeKrqGcBjN1vmzcz72iCymfZvVhsX/h2wVXUkL2NOkxwX3dMXpGsdWUSt+fpZPNemqpg8Gy0HJKo/Jbw3JWnSDtK2tDeJ6YD4eFVlUOwe+PX6bTqzUq6P+x/uxDyxP2nzd2WdP+/1pK6TT9xeNfwmnkCIK1X3R5xVpbIho7vXoOx7KYdQAAAPDL8ZpZRVdTMo6UYRZdTbn4mvl0l9LHRZdTLupEryly4k5fMrAy1Ha35Y6U2p7cMjtFF1QmaluRv4ZyLUmHcLKicGpy0nEI50IczgnhnEnDUVp7hJOVhCPr7p706cPpO9v0ZWN2CEf51m63TW02s4osrAyq0jj9qV+T9su4HA+rrjsvtKxSeNBfknAeNEk/zMQTMyIRjtD053H8U2RVHbvhk3xYpSRpbHc+/ZiKw3kaOZHxZPTcPWRTc0dtrqtimt5SJvEleNg9nhkr3RfCiUXhyLIrmXfy6exPC58JJxaFU5O/h+HZmXGbYbWn6Uo8kBQ5G87DXC26rlJY6dnLqcOUw2VDatluyWfZ3IVzVvFE/3G0yabT+ioVXVKJBPMws1TJ338wGWetdPk04biSVnQ95ZLMO0pLqWmf+ZqqkqOnmu4m7jSjb62XcDX3F3mtPrA0nGoedSZtolVqqU3CMDTv1dxGH9jb/ckyN3IoCX8c48bGk8pOiK25cbXsWXHjH99RvW3kbGyoaiDErpJtZ/fe8W5O5z2tRNMO3t7vifourcU+lGGrN3uKsXu92JKE8xSqYrg4vusxHKMnvNMft9gdnxBqnN90beWFc/CzcJzp1SFO/aJVr3LZZPh6Hs5QvT53vQ5ncdUm41XNe8Rna+rhj7Hh5fQXbyj6/jGRTvUYiXGjcwWDbf6Om7woiOZgsI+jefndJZwvV0ddfL63iDds629/1vB4lJdkadiDtw+xtMjqv3k44XX4b+7j3znO/hvYvWs43da/3YEvGEmnM7Y8TQgAAAAAAPCrMW795w4AAAAAAAAAAAAAAAAAAAAAAAAAgMTftIc9JcLHctgAAAAASUVORK5CYII=

### Icon link

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARwAAACxCAMAAAAh3/JWAAAAulBMVEUAAAAtLS2fn6AcW4ZsbWxLTUtCRUP4/v8XWYU4bJIAU4EDVYKnqavG1+Nsbm/k5+qEo7sICQgATn7u9vxRUlJ4eHkZGhk/QD9eX1+CgoJgY2GyxtUVFRW7zdrv9PjX5O6Ojo+Wlpe/wcK0t7nGy87P1NYgIyGfp6pCSE3b3+FJTEmnt8F1f4WDh4k2OTicoJ1qc3k1PUJKeJpqi6aNqL1fh6V0lrBRfJ2dtskoY4xkiqZXV1kzNTQmKCbHY3dbAAADU0lEQVR4nO3ba3eiVhiG4e0RIiggoCh4QBOtNkPbzIQZo/n/f6ugoKiYSbu6CpPc1ycXbPTN4z5ABCEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfEzG1HeKrqGcBjN1vmzcz72iCymfZvVhsX/h2wVXUkL2NOkxwX3dMXpGsdWUSt+fpZPNemqpg8Gy0HJKo/Jbw3JWnSDtK2tDeJ6YD4eFVlUOwe+PX6bTqzUq6P+x/uxDyxP2nzd2WdP+/1pK6TT9xeNfwmnkCIK1X3R5xVpbIho7vXoOx7KYdQAAAPDL8ZpZRVdTMo6UYRZdTbn4mvl0l9LHRZdTLupEryly4k5fMrAy1Ha35Y6U2p7cMjtFF1QmaluRv4ZyLUmHcLKicGpy0nEI50IczgnhnEnDUVp7hJOVhCPr7p706cPpO9v0ZWN2CEf51m63TW02s4osrAyq0jj9qV+T9su4HA+rrjsvtKxSeNBfknAeNEk/zMQTMyIRjtD053H8U2RVHbvhk3xYpSRpbHc+/ZiKw3kaOZHxZPTcPWRTc0dtrqtimt5SJvEleNg9nhkr3RfCiUXhyLIrmXfy6exPC58JJxaFU5O/h+HZmXGbYbWn6Uo8kBQ5G87DXC26rlJY6dnLqcOUw2VDatluyWfZ3IVzVvFE/3G0yabT+ioVXVKJBPMws1TJ338wGWetdPk04biSVnQ95ZLMO0pLqWmf+ZqqkqOnmu4m7jSjb62XcDX3F3mtPrA0nGoedSZtolVqqU3CMDTv1dxGH9jb/ckyN3IoCX8c48bGk8pOiK25cbXsWXHjH99RvW3kbGyoaiDErpJtZ/fe8W5O5z2tRNMO3t7vifourcU+lGGrN3uKsXu92JKE8xSqYrg4vusxHKMnvNMft9gdnxBqnN90beWFc/CzcJzp1SFO/aJVr3LZZPh6Hs5QvT53vQ5ncdUm41XNe8Rna+rhj7Hh5fQXbyj6/jGRTvUYiXGjcwWDbf6Om7woiOZgsI+jefndJZwvV0ddfL63iDds629/1vB4lJdkadiDtw+xtMjqv3k44XX4b+7j3znO/hvYvWs43da/3YEvGEmnM7Y8TQgAAAAAAPCrMW795w4AAAAAAAAAAAAAAAAAAAAAAAAAgMTftIc9JcLHctgAAAAASUVORK5CYII=

### Long description

This is the chrome dinosaur game for the 3ds, FUUUUUN.

### Screenshots

![download](https://github.com/user-attachments/assets/f25aec58-20aa-48d9-bf0a-8263bce66a1d)

### GitHub repository of the app

https://github.com/BlyZeDev/T-Rex-Game-3DS

### Author

BlyZeDev

### Short description

Simple chrome dino game for 3DS

### Source code link

https://github.com/BlyZeDev/T-Rex-Game-3DS/archive/refs/tags/v1.2.0.zip

### Creation date

October 23

### Last update date

October 23

### Website link

https://github.com/BlyZeDev/T-Rex-Game-3DS

### Wiki link

https://www.gamebrew.org/wiki/T-Rex_Runner_Game_DS

### Download page link

https://github.com/BlyZeDev/T-Rex-Game-3DS

### Version number

v1.2.0

### Version title

v1.2.0

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by BlyZeDev** [comment]
I already requested my game
