### ISSUE TITLE
Famidash 3DS Inject

### ISSUE THREAD

**Issue by VandGD** [Universal-Team/db#292]
### Title

Famidash 3DS Inject

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0004000000D0EB00

### Image link

https://imgur.com/a/titlescreen-mYSk2Gs

### Icon link

https://avatars.githubusercontent.com/u/165867289?s=48&v=4

### Long description

The only compatible and working way to play Geometry Dash on 3DS

### GitHub repository of the app

https://github.com/VandGD/3DS-VC-Famidash/releases/tag/FDVC3DS-V2

### Author

VandGD

### Short description

Famidash Inject for 3DS

### Source code link

https://github.com/VandGD/3DS-VC-Famidash

### Creation date

10. 12. 2024

### Last update date

12. 27. 2024

### Website link

https://github.com/VandGD/3DS-VC-Famidash/releases/tag/FDVC3DS-V2

### Download page link

https://github.com/VandGD/3DS-VC-Famidash/releases/tag/FDVC3DS-V2

### Version number

v2

### Version title

v2

### Download link(s)

https://github.com/VandGD/3DS-VC-Famidash/releases/tag/FDVC3DS-V2

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Epicpkmn11** [comment]
Sorry, but after some thought we have decided to only allow actual 3DS/DS homebrew on Universal-DB. As this is an NES homebrew in a VC inject I am closing the issue.
