### ISSUE TITLE
Nagito 2

### ISSUE THREAD

**Issue by hanimelewd** [Universal-Team/db#34]
**Name of the app**
Nagito 2

**System(s)**
3DS

**Categories**
Just for Fun

**Image link**
![sussy](https://user-images.githubusercontent.com/86051816/122387005-6a19df80-cf3c-11eb-9aa8-da35e1ce5cf4.png)

**Icon link**
![icon](https://user-images.githubusercontent.com/86051816/122386483-ed870100-cf3b-11eb-8d2b-f165e978c195.png)

**Long description**
nagito komaeda. must have dspfirm.cdc to function correctly.

**Screeshots**
![sussy](https://user-images.githubusercontent.com/86051816/122387040-743bde00-cf3c-11eb-8a55-8fd44ecd836b.png)

**GitHub repository of the app**
https://github.com/hanimelewd/nagitonuts

**Author**
blacked.com

**Short description**
nagito komaeda.

**Source code link**
https://github.com/hanimelewd/nagitonuts/blob/main/main.c

**Creation date**

**Last update date**

**Website link**
https://github.com/hanimelewd/nagitonuts

**Wiki link**

**Download page link**

**Version number**
2

**Version title**
Release

**Last update date**

**Download link(s)**
[cia](https://github.com/hanimelewd/nagitonuts/raw/main/nagito.cia)
[3dsx](https://github.com/hanimelewd/nagitonuts/raw/main/nagito.3dsx)

- [x] I am the app developer or have permission from the app developer to make this request

if you could add an app that says "fuck you" when you press a button, i think mine would be good enough to be added as well. :)

**Comment by hanimelewd** [comment]
nagito 1 coming soon

**Comment by hanimelewd** [comment]
shoutout to "a unfunny person" and "lifehackerhansol"

**Comment by hanimelewd** [comment]
https://github.com/hanimelewd/nagitonuts/blob/main/main.c pls no steal this costs 1 million dolar

**Comment by NightYoshi370** [comment]
Please change your ReadME to describe what the app actually does. I do not want to sit through hundreds of lines of code to learn it. Also, the current readme is not professional in the slightest, which makes me hesitant on accepting this app request.

Also:

> if you could add an app that says "fuck you" when you press a button, i think mine would be good enough to be added as well. :)

That's not how this works. It's not that one app gets added so another one also deserves a spot. Each app get's looked at individually.

**Comment by hanimelewd** [comment]
my apollogies sir i have fixed it i love nagito
