### ISSUE TITLE
Little translation problems (french)

### ISSUE THREAD

**Issue by Sirix1995** [Universal-Team/db#37]
French name for the main page is "Accueil". Not "Acceuil".

Also, in the introduction text :

 "régulièrement mises à jour pour vous assurer que vous obteniez les dernières versions"

I'm pretty sure that the right conjugation is "obtenez", not "obteniez".

**Comment by SuperSaiyajinStackZ** [comment]
If you want to fix those, you can help translating them on [crowdin](https://crowdin.com/project/universal-db).
