### ISSUE TITLE
Browser Youtube BETA

### ISSUE THREAD

**Issue by Clow114514** [Universal-Team/db#38]
Make Youtube more comfortable

Support for long videos and live viewing

You can also login to comment

Download links
https://github.com/Clow114514/Browser-Youtube-BETA/releases/tag/Youtube

![1200px-YouTube_social_white_square_(2017) svg](https://user-images.githubusercontent.com/81944227/127774307-a7119ec5-1511-486f-8d4e-82a648025c71.png)

**Comment by Clow114514** [comment]
？？？？

**Comment by Clow114514** [comment]
miss

**Comment by Epicpkmn11** [comment]
We prefer apps on Universal-DB to be more than just test apps, forwarders, etc, as this seems to just be a browser forwarder CIA I'm going to close this.

Also it uses the official splash on loading which I believe is at best questionable legality wise, and doesn't have source code in the repo which while not required is preferred to get onto Universal-DB.
