### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by zaidboss343** [Universal-Team/db#39]
**Name of the app**

YouTube

**System(s)**
New 3DS systems

**Categories**

Videos

**Image link**

**Icon link**

**Long description**
YouTube for New 3DS. Use this because YouTube for 3DS is not on eshop and ThirdTube keeps on buffering. Made with Web Forwarder to make website/web apps to a 3DS app or CIA format. 

**Screenshots**

**GitHub repository of the app**

**Author**

**Short description**

**Source code link**

**Creation date**

**Last update date**

**Website link**

**Wiki link**

**Download page link**

**Version number**
1.0

**Version title**

**Last update date**

**Download link(s)**

- [x] I am the app developer or have permission from the app developer to make this request

**Comment by SuperSaiyajinStackZ** [comment]
> We prefer apps on Universal-DB to be more than just test apps, forwarders, etc, as this seems to just be a browser forwarder CIA I'm going to close this.

(See https://github.com/Universal-Team/db/issues/38 for already such a type of request and the last comment).
