### ISSUE TITLE
Web brower

### ISSUE THREAD

**Issue by haru87582719** [Universal-Team/db#40]
**Name of the app**

**System(s)**

**Categories**

**Image link**

**Icon link**

**Long description**

**Screenshots**

**GitHub repository of the app**

**Author**

**Short description**

**Source code link**

**Creation date**

**Last update date**

**Website link**

**Wiki link**

**Download page link**

**Version number**

**Version title**

**Last update date**

**Download link(s)**

- [ ] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
empty template, this form is for requesting existing apps be added to the database
