### ISSUE TITLE
Inform users that nightly downloads are not recommended for regular use

### ISSUE THREAD

**Issue by lifehackerhansol** [Universal-Team/db#42]
A commonly brought up issue within the Nintendo Homebrew help channels is people accidentally downloading the nightly version of TWiLight Menu++ with no idea what "nightly" means.

A nice touch would be to inform the user that this is a "nightly" and people should use the release build instead. (Perhaps a toggle option is also nice. Maybe there could be some sort of flag that defines release and not-release?)

**Comment by lifehackerhansol** [comment]
I wasn't sure if this was supposed to be app request or site request. It's technically neither. It _is_ unistore related, as far as I'm concerned, though.

**Comment by Epicpkmn11** [comment]
This seem good? Unfortunately can't really do a proper note that's dismissible and such for nightlies without a UU update, but definitely worth considering for v4 I think.

![スクリーンショット 2021-09-29 2 32 13](https://user-images.githubusercontent.com/41608708/135223377-0c59b0d7-cf76-428f-87df-179e8009f8f8.png)

**Comment by lifehackerhansol** [comment]
I think that's basically everything I ask for, yeah. 

Most projects in this repo _are_ done via release and optional nightlies, so a built-in flag to the unistore spec would not be a bad idea imo. It would definitely have to be in a separate release as you said.

**Comment by Epicpkmn11** [comment]
Added in Universal-Team/Universal-Updater@3cde3a3a1f19571338f82484892a690d7b5905ba and 2d6d622044f16866e47170c2ec6e9559bfd7c512
