### ISSUE TITLE
instagram

### ISSUE THREAD

**Issue by pepelontie** [Universal-Team/db#44]
**Name of the app**

**System(s)**

**Categories**

**Image link**

**Icon link**

**Long description**

**Screenshots**

**GitHub repository of the app**

**Author**

**Short description**

**Source code link**

**Creation date**

**Last update date**

**Website link**

**Wiki link**

**Download page link**

**Version number**

**Version title**

**Last update date**

**Download link(s)**

- [ ] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Do you have a link to this instagram app you want added? This is not a place to request someone makes an app, it's to request an existing app be added to Universal-DB.

Closing as afaik the app doesn't exist and the template wasn't filled out.
