### ISSUE TITLE
App request- PKSM

### ISSUE THREAD

**Issue by Eternal-plasma** [Universal-Team/db#5]
**Name of the app**
PKSM

**System(s)**
3ds

**Categories**
Save Tools

**Image link**
https://raw.githubusercontent.com/FlagBrew/PKSM/master/assets/banner.png

**Icon link**
Same as Image

**Long description** 

Multipurpose and portable save manager for generations III to VIII, programmed in
C++.

* Supports original cartridges and digital copies of games from FrLgRSE to SwSh
* Allows on-the-fly modifications to all of your data
* Allows internal and resizable offline storage to store your Pokémon
* Capable of running custom scripts to allow injection of arbitrary data into
  your saves
* Interfaces with multiple ad-hoc programs running on your computer, web browser
  or smartphone
* Capable of scanning QR codes to inject both .pkx files or event wondercards
* Contains an offline wondercard database to get events from old distributions
* Capable of automatic verification and legalization of all your data

**We do not support or condone cheating at the expense of others. Do not use
significantly edited Pokémon in battle or in trades with those who are unaware
edited Pokémon are in use.**

**GitHub repository of the app**
https://github.com/FlagBrew/PKSM

**Author**

**Short description**

**Source code link**

**Creation date**

**Last update date**

**Website link**

**Wiki link**

**Download page link**

**Version number**

**Version title**

**Last update date**

**Download link(s)**

**File name(s)**

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Eternal-plasma** [comment]
Wait links dissapeared

**Comment by L-i-n-u-x-C-a-t** [comment]
Sadly flagbrew doesn't want his apps to be in Universal-DB, that's why we removed checkpoint too.

**Comment by SuperSaiyajinStackZ** [comment]
Someone of the FlagBrew Team must approve it here, else we cannot accept this request. 😛

**Comment by Eternal-plasma** [comment]
ok I thought it was ok because of the GNU General Public License v3.0 thanks anyway

**Comment by Epicpkmn11** [comment]
I'm gonna tag @piepie62 and @BernardoGiordano on this, if you've changed your minds on having your apps on Universal-DB I'd be happy to add them, but if not then this can be closed. If there's not a reply within a week or so I'll assume that's a no.
