### ISSUE TITLE
A-client-for-Discord-for-3DS

### ISSUE THREAD

**Issue by XeathJP** [Universal-Team/db#57]
**3Discord**

**3DS**

**Chat**

![banner](https://user-images.githubusercontent.com/96643570/150622379-f0a9da85-4dc0-443c-a090-b73ebbeae894.png)

![icon](https://user-images.githubusercontent.com/96643570/150622398-cc21bfb2-e4b8-41ef-b038-6bac262b53cf.png)

**I can use discord direct messages on my 3DS! Direct message only, so no need to worry about getting banned!**

![2011-01-06_13-43-54 744_top](https://user-images.githubusercontent.com/96643570/150622601-b0d4a17b-406e-4144-b5bc-efd13cb798fa.png)
![2011-01-06_13-43-54 744_bot](https://user-images.githubusercontent.com/96643570/150622607-8a458f18-92d3-459a-9f23-ed218eeeaeb3.png)

https://github.com/XeathJP/A-client-for-Discord-for-3DS

Source/cheuble
build/Xeath
Special thanks/ARM11&windows server2003

Safe and secure 3Discord

[**Source code link**](https://github.com/XeathJP/A-client-for-Discord-for-3DS)

2021/09/12

2022/01/20

**Website link**

**Wiki link**

https://github.com/XeathJP/A-client-for-Discord-for-3DS/releases

v0.1

**Version title**

2022/01/20

**Download link(s)**

- [x] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Sorry but I'm going to say no to adding this to Universal-DB, it's against Discord's TOS to use alternative clients and I'd rather not have that on here since if it's popular chances are someone will get banned for using it at some point.
