### ISSUE TITLE
HokakuCTR

### ISSUE THREAD

**Issue by lifehackerhansol** [Universal-Team/db#66]
### Title

HokakuCTR

### System(s)

3DS

### Categories

Utility

### Image link

N/A

### Icon link

N/A (plugin) (Pretendo Network icon maybe?)

### Long description

A 3DS game plugin (3GX) to dump the RMC communication between 3DS games and NEX. The traffic is dumped to the SD into pcap files.

### GitHub repository of the app

https://github.com/PretendoNetwork/HokakuCTR

### Author

Pretendo Network

### Short descrption

A 3DS game plugin (3GX) to dump the RMC communication between 3DS games and NEX. The traffic is dumped to the SD into pcap files.

### Source code link

https://github.com/PretendoNetwork/HokakuCTR

### Creation date

2022/02/16

### Last update date

2022/02/16

### Website link

https://pretendo.network/

### Download page link

https://github.com/PretendoNetwork/HokakuCTR/releases

### Version number

v1.0

### Version title

Initial Release

### Other notes

See #non-homebrew in Discord for proof of permission to add to Universal-DB.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Whoops, forgot to close the issue. Added in 05cf6f5297c03a7e4be3320c35b9a78fb26f3ee7.
