### ISSUE TITLE
Flappy-Bird

### ISSUE THREAD

**Issue by Tobi-D7** [Universal-Team/db#68]
### Title

Flappy.-Bird

### System(s)

3DS

### Categories

Game

### Image link

https://raw.githubusercontent.com/NPI-D7/Flappy-Bird/master/app/banner.png

### Icon link

https://raw.githubusercontent.com/NPI-D7/Flappy-Bird/screenshots/app/icon.png

### Long description

# Flappy-Bird 
<img href="" alt="Discord" src="https://img.shields.io/discord/961610973066702889?style=for-the-badge">
[Discord](https://discord.gg/XuX6EN8dyt)

The ground is a bit buggy currently!

<details closed>
<summary>Screenshots</summary>
<br>

![Fb](https://user-images.githubusercontent.com/71647024/162621212-528316ee-5ddf-42cb-8efb-28ab9be001f0.png)
![Diffrent Colers](https://user-images.githubusercontent.com/71647024/162621218-0e25ceca-5885-457b-a45c-3290e3e25ebc.png)
![Flying](https://user-images.githubusercontent.com/71647024/162621219-9b32029d-609f-443f-b85b-6cc2a4a79c2b.png)
![Gover](https://user-images.githubusercontent.com/71647024/162621226-3b254304-3fc5-411f-8753-42993771c9cd.png)
</details>

# QR-Code
<img src="https://user-images.githubusercontent.com/71647024/162621632-443d20c7-c848-4ba2-a26d-3a8e94412c20.png" width="300">

# Credits
devkitpro: for libctru, citro2/3d.
Dong Nguyen, .Gears: for the Game.

### Screenshots

![Flying](https://user-images.githubusercontent.com/71647024/162623020-3e4f2972-ddf1-4558-95ac-c4c3efb01f86.png)
![Gover](https://user-images.githubusercontent.com/71647024/162623021-ea478f31-2bcc-41f1-a983-56d926ac853f.png)
![Diffrent Colers](https://user-images.githubusercontent.com/71647024/162623022-5c68a911-022a-489f-8ab8-262f8e09f6cd.png)
![Fb](https://user-images.githubusercontent.com/71647024/162623023-4584972f-1443-4804-b9c2-6ffeee5afff1.png)

### GitHub repository of the app

https://github.com/NPI-D7/Flappy-Bird/

### Author

NPI-D7

### Short descrption

A Clone of Flappy-Bird for the 3ds.

### Source code link

https://github.com/NPI-D7/Flappy-Bird/

### Creation date

10.04.2022

### Last update date

10.04.2022

### Download page link

https://github.com/NPI-D7/Flappy-Bird/releases

### Version number

1.0.0

### Version title

Flappy-Bird 1.0

### Download link(s)

https://github.com/NPI-D7/Flappy-Bird/releases/download/1.0.0/Flappy-Bird.3dsx
https://github.com/NPI-D7/Flappy-Bird/releases/download/1.0.0/Flappy-Bird.cia

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Added by 61440df61e868fe1e1a728d82723b786877194b5
