### ISSUE TITLE
FBI Spanish

### ISSUE THREAD

**Issue by Nylox333** [Universal-Team/db#75]
### Title

FBI En Español

### System(s)

3DS

### Categories

Utility

### Image link

https://i.imgur.com/XllTRgk.png

### Icon link

https://i.imgur.com/XllTRgk.png

### Características

- Explore y modifique la tarjeta SD, las fotos TWL, los sonidos TWL, guarde datos y ext guarde datos. 

- Exporte, importe y borre datos guardados de cartuchos DS. 

-  Exporte, importe y elimine valores seguros de datos guardados. 

- Instale títulos/boletos desde un sistema de archivos, a través de una red local o a través de Internet con una URL o un código QR. 

> Se importan automáticamente las semillas del título en la instalación, ya sea desde Internet o desde la tarjeta SD. 

- Explore y elimine títulos pendientes (actualizaciones descargadas, títulos de eShop en curso, etc.). 

- Personalice la apariencia colocando reemplazos para los recursos de RomFS en "sdmc:/fbi/theme/". 

-  Solo disponible cuando se ejecuta desde CIA, 3DS o 3DSX bajo Luma3DS: 

> Explore y modifique CTR NAND, TWL NAND y datos guardados del sistema. 

> Vuelque la NAND original sin procesar en la tarjeta SD. 

> Inicie títulos instalados en el sistema.

### Screenshots

![Picsart_22-05-02_18-36-14-691](https://user-images.githubusercontent.com/103130807/166283399-a6016e95-907b-4186-b6ce-746fad469b51.jpg)

### GitHub repository of the app

https://github.com/LopezTutoriales/FBI-Spanish

### Author

LopezTutoriales

### Short descrption

Administrador de títulos de código abierto para 3DS

### Creation date

2021/05/15

### Last update date

2022/05/02

### Download page link

https://github.com/LopezTutoriales/FBI-Spanish/releases

### Version number

2.6.1

### Version title

v2.6.1

### Download link(s)

https://github.com/LopezTutoriales/FBI-Spanish/releases/download/2.6.1/FBI_ESP.zip

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Alexanderjan100** [comment]
![Image](https://github.com/user-attachments/assets/ae64f716-d4b6-4f2b-8594-d290008fd5fb)
The Simpsons Hit & Run 3ds Und PC - Logo
@LopezTutoriales
