### ISSUE TITLE
Update to the submitted version of atari800 I built

### ISSUE THREAD

**Issue by RandomMan25XX** [Universal-Team/db#79]
### Title

Atari800

### System(s)

3DS

### Categories

Emulator

### Image link

https://imgur.com/N2l1KgM

### Icon link

https://imgur.com/AEVj5DE

### Long description

Atari 8-bit computer and 5200 console emulator

### GitHub repository of the app

https://github.com/RandomMan25XX/atari800

### Author

Adrian Siekierka

### Short description

Atari 8-bit/5200 Emulator

### Website link

https://atari800.github.io/

### Version number

Version_3DS_0.3.6

### Download link(s)

https://github.com/RandomMan25XX/atari800/releases/tag/Version_3DS_0.3.6

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by RandomMan25XX** [comment]
Probably best to not add this update until I figure out why the keyboard is missing

**Comment by TheGhostboi64** [comment]
You should've done this after you get the keyboard working. It might even already be in UU after a few days while you still would be fixing the keyboard. Just saying.

**Comment by TheGhostboi64** [comment]
Otherwise I think UU would be nice enough to wait

**Comment by RandomMan25XX** [comment]
> You should've done this after you get the keyboard working. It might even already be in UU after a few days while you still would be fixing the keyboard. Just saying.

I just updated the cia in my forked repository to fix the issue

**Comment by Epicpkmn11** [comment]
Closing as Universal-DB is already using your fork for the releases so update tracking is automatic.
