### ISSUE TITLE
Incorrect authorship information for atari800-3ds

### ISSUE THREAD

**Issue by asiekierka** [Universal-Team/db#84]
The build of atari800-3ds distributed on Universal-DB is not an official build made by myself (I tend to only distribute my homebrew in .3dsx format). It also doesn't seem to contain the patches made to build the .cia version, which may constitute a violation of the GPL. While I am not particularly interested in pursuing the above-mentioned potential violation myself, I do not wish to see builds I have not made myself to be misattributed to me. As such, I would like it to either:

(a) use an official build from my repository -> https://github.com/asiekierka/atari800 (I'll make one this evening - I'd like to do some source code updates),
(b) credit RandomMan25XX for the release, as opposed to myself.

**Comment by asiekierka** [comment]
Just put one up. Keep in mind that I have no plans to make CIA builds of my homebrew, only 3DSX - I have no issue with a fork existing, just with potential misattribution of the build's origin.

Thank you for the prompt response!

**Comment by asiekierka** [comment]
From my side, the issue is closed. If you want to do anything further, that's up to you.

**Comment by asiekierka** [comment]
I see you've gone with adding both builds anyway. As a word of caution - I plan to be pushing releases for both the 3DS and NDS port on the same repository.

**Comment by Epicpkmn11** [comment]
ah, if you could just attach both the 3DSX and NDS files to every release then that shouldn't cause issues, I'll just set it to show in the DS section too.

If you only do one or the other I'll probably need to hardcode the download links since U-DB only checks the latest release, but that's not too big a deal either.

**Comment by asiekierka** [comment]
On second thought, I'll just move them to separate repositories. This will make it easier for GitHub users as well.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/atari800-3ds/releases/latest
https://github.com/asiekierka/atari800-nds/releases/latest

Not sure if there's much point to listing atari800-nds; see the release description for my rationale.

**Comment by Epicpkmn11** [comment]
Alright, I've updated the 3DS repo and left it at that at the moment. Please feel free to let us know if you'd ever like the DS one added as well.
