### ISSUE TITLE
RecoveryFox

### ISSUE THREAD

**Issue by ErgFox3DS** [Universal-Team/db#85]
### Title

RecoveryFox

### System(s)

3DS

### Categories

Save Tool, Luma3DS

### Long description

recovery for 3ds on goodmode9!

### GitHub repository of the app

https://github.com/ErgFox3DS/RecoveryFox/blob/main/recoveryfox.gm9

### Author

ErgFox3ds

### Short description

a recovery for 3ds on goodmode9

### Creation date

10/06/22

### Last update date

10/06/22

### Download page link

https://github.com/ErgFox3DS/RecoveryFox/blob/main/recoveryfox.gm9

### Version number

v1

### Version title

v1

### Download link(s)

https://github.com/ErgFox3DS/RecoveryFox/blob/main/recoveryfox.gm9

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by lifehackerhansol** [comment]
What does this do that the GM9Megascript doesn't?

**Comment by NightScript370** [comment]
![download (1).png](https://user-images.githubusercontent.com/18664762/173214439-5d2fa781-c5be-465a-8313-ab310945690f.png)

**Comment by ErgFox3DS** [comment]
bruhhhh
