### ISSUE TITLE
Luma 3DS (Nanquitas) Spanish

### ISSUE THREAD

**Issue by Nylox333** [Universal-Team/db#87]
### Title

Luma 3DS (Nanquitas) En Español

### System(s)

3DS

### Categories

Utility, FIRM, Luma3DS

### Image link

https://i.imgur.com/OMuSLEV.jpg

### Icon link

https://i.imgur.com/OMuSLEV.jpg

### GitHub repository of the app

https://github.com/LopezTutoriales/Luma3DS_3GX_Loader_ESP

### Author

LopezTutoriales

### Short description

Custom Firmware Luma3DS modificado por Nanquitas para cargar plugins

### Creation date

2022/06/19

### Last update date

2022/06/19

### Download page link

https://github.com/LopezTutoriales/Luma3DS_3GX_Loader_ESP/releases

### Version number

11.0

### Version title

v11.0

### Download link(s)

https://github.com/LopezTutoriales/Luma3DS_3GX_Loader_ESP/releases/download/v11.0/boot.firm

https://github.com/LopezTutoriales/Luma3DS_3GX_Loader_ESP/releases/download/v11.0/boot.3dsx

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Added by 29a571b577d50083e3096a5430a8d16776af85e3, sorry about the delay
