### ISSUE TITLE
Download CTRtransfert file to downgrade and fix various issues with your console

### ISSUE THREAD

**Issue by The-Mov-Collector** [Universal-Team/db#88]
### Title

CTRtransfert Download

### System(s)

3DS

### Categories

Save Tool

### Icon link

https://ia902505.us.archive.org/18/items/ctrtransfert-ux-ressources/icon.png

### Author

Hidden

### Download link(s)

CTRtransfert 11.5.0-38E for old 3DS (Europe)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/OLD%203DS/11.5.0-38E_ctrtransfer_o3ds.zip

CTRtransfert 11.5.0-38E for new 3DS (Europe)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/NEW%203DS/11.5.0-38E_ctrtransfer_n3ds.zip

CTRtransfert 11.5.0-38J for old 3DS (Japan)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/OLD%203DS/11.5.0-38J_ctrtransfer_o3ds.zip

CTRtransfert 11.5.0-38J for new 3DS (Japan)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/NEW%203DS/11.5.0-38J_ctrtransfer_n3ds.zip

CTRtransfert 11.5.0-34K for new 3DS (Korea)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/NEW%203DS/11.5.0-34K_ctrtransfer_n3ds.zip

CTRtransfert 11.5.0-38U for old 3DS (USA)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/OLD%203DS/11.5.0-38U_ctrtransfer_o3ds.zip

CTRtransfert 11.5.0-38J for new 3DS (USA)
https://files.darkmatternetworks.co.uk/Tutorials/3DS%20Region%20Change/CTRTRANSFER/NEW%203DS/11.5.0-38U_ctrtransfer_n3ds.zip

### Developer permission

- [x] I am the app developer or have permission from the app developer to make this request

**Comment by NightScript370** [comment]
> I am the app developer or have permission from the app developer to make this request
Huh, a Nintendo representative allowing CTRTransfer images? Next thing you'll tell me, you're allowing fangames that recreate already existing games for PC to be published.

Yeah, no. Closing....
