### ISSUE TITLE
CTGP-7 Save Transfer Tool

### ISSUE THREAD

**Issue by CyberYoshi64** [Universal-Team/db#89]
### Title

CTGP-7 Save Transfer Tool

### System(s)

3DS

### Categories

Utility, Save Tool

### Image link

https://github.com/CyberYoshi64/CTGP7-SaveTransfer/raw/main/app/banner.png

### Icon link

https://github.com/CyberYoshi64/CTGP7-SaveTransfer/raw/main/app/icon.png

### Long description

This tool allows you to copy your save data between CTGP-7 and Mario Kart 7.
Supported are Physical and Digital versions of all regions.

You can either just copy your stats or include your Time Trial ghosts as well.
(Note: Only those for the original tracks are considered. Such for custom tracks are left alone.)

### Screenshots

https://github.com/CyberYoshi64/CTGP7-SaveTransfer/raw/main/app/screenshots/1-main_menu.png
https://github.com/CyberYoshi64/CTGP7-SaveTransfer/raw/main/app/screenshots/2-transfer.png
https://github.com/CyberYoshi64/CTGP7-SaveTransfer/raw/main/app/screenshots/3-cycleContinuation.png

### GitHub repository of the app

https://github.com/CyberYoshi64/CTGP7-SaveTransfer

### Short description

Save data copier between MK7 and CTGP-7

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Whoops, sorry for the delay. Somehow I missed this for a few days.

**Comment by CyberYoshi64** [comment]
It's fine. Tho I was scared a bit lmao
