### ISSUE TITLE
navegador 

### ISSUE THREAD

**Issue by wilhd2** [Universal-Team/db#9]
hello I am not your programmer nor do I know if what I am going to ask for is more possible, it would be nice to have applications like tweeting for 3ds would be really cool. more already q in most cases twitwer only needs an updated browser. I think idela will have an updated browser for 3ds
if possible I believe the community would love it.

**Comment by SuperSaiyajinStackZ** [comment]
This is not the place for making app creation requests.

**Comment by wilhd2** [comment]
sorry for something wrong then because the app download page has a link with the caption just to make aps requests and that you brought here. anyway what the right place would be. Would you help me ?

**Comment by SuperSaiyajinStackZ** [comment]
This is the place for requesting apps which already exist to be added to Universal-DB. Maybe look around on GBATemp or Reddit to make the request.

**Comment by wilhd2** [comment]
OK thank you
