### ISSUE TITLE
3DS Gamepad

### ISSUE THREAD

**Issue by LunaAbreu** [Universal-Team/db#91]
### Title

3DS Gamepad for Wii U

### System(s)

3DS

### Categories

Utility

### Image link

https://images.app.goo.gl/qexXf93dvacWjtf28

### Icon link

https://images.app.goo.gl/yfqvq5r72PVFR5YT8

### Long description

Wii U Gamepad for 3DS

### Author

Lynix

### Short description

3DS Gamepad

### Source code link

3DS

### Creation date

08/03/2022

### Last update date

08/03/2022

### Version number

1.0

### Version title

Gamepaxx

### Other notes

Hello everyone, I created an application (which is considered homebrew) which is a Wii U Gamepad for the 3DS.

The utility of the application is:

- The fact of using the touch screen of the Wii U Gamepad with his 3DS,

- To be able to watch the content broadcast by the console on the Gamepad,

- Be able to use the 3DS as a Wii U Gamepad (Only available for the New Nintendo 3DS edition, I will think about it in the future for a way to perform the same for Old 3DS)

That was it, updates will be coming.

Instructions for using the application are available in the application menu.

🚨/!\ - To make the 3DS like a Gamepad, you must follow the instructions in the user manual, you will have to click in "Connect the 3DS" to associate the logos with those displayed by the console on the television, if an error occurs , restart the application and the console. - /!\🚨

P.S: You should know that when the 3DS is connected, the Gamepad is always connected because for console security reasons the 3DS is not and will surely not be used and executed as the main Gamepad of the Wii U.

No need to hack your Wii U to use the application, but the use of a CWF on the 3DS is necessary, Luma3DS for example.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Do you have a download link? I see you have [a repo](https://github.com/LunaAbreu/3dsgamepad) on your account, but there are no files or releases and you didn't put a download links here...

I can't exactly add something if it doesn't exist ;P

**Comment by EggFox** [comment]
download link bro...

**Comment by Epicpkmn11** [comment]
Closing due to lack of a response and no download.
