### ISSUE TITLE
3DS Sorting Algorithm Visualizer

### ISSUE THREAD

**Issue by memeToasty** [Universal-Team/db#93]
### Title

3DS Sorting

### System(s)

3DS

### Categories

Game

### Image link

https://github.com/memeToasty/3ds_sorting/blob/main/meta/banner.png?raw=true

### Icon link

https://github.com/memeToasty/3ds_sorting/blob/main/meta/icon.png?raw=true

### Long description

This application serves no purpose other than to show some visualisation of certain sorting algorithms, like one would know from famous YouTube videos.

If you encounter an error, let me know: [Create Issue](https://github.com/memeToasty/3ds_sorting/issues/new)

### Screenshots

![Image](https://user-images.githubusercontent.com/31214870/188508516-f80b4d67-cf53-4fbf-99c4-97c7b063dc4e.png)
![Image](https://user-images.githubusercontent.com/31214870/188508568-540b00ad-10a0-4d03-9fb0-98b30143a096.png)

### GitHub repository of the app

https://github.com/memeToasty/3ds_sorting

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Sorry about the delay, added now!
