### ISSUE TITLE
The Html Maker! 

### ISSUE THREAD

**Issue by Tylerpizza11** [Universal-Team/db#96]
### Title

The Html maker!

### System(s)

3DS

### Categories

Utility

### Long description

This was made by tylerpizza11. it using vscode and devkitpro for the 3ds and 2ds.

### GitHub repository of the app

https://github.com/Tylerpizza11/Html-Maker/blob/main/Html-Maker!.3dsx

### Author

Tylerpizza11

### Short description

Html Maker!

### Source code link

https://github.com/Tylerpizza11/Html-Maker/blob/main/Source%20Code.zip

### Creation date

10/10/2022

### Last update date

10/10/2022

### Download page link

https://github.com/Tylerpizza11/Html-Maker

### Version number

0.0.1

### Version title

Html Maker!

### Download link(s)

https://github.com/Tylerpizza11/Html-Maker/blob/main/Html-Maker!.3dsx

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by NightScript370** [comment]
First immediate red flag is that the source is here and uploaded on GitHub, but if you're providing the source, you might as well upload it as source rather than through an archive.
I'm gonna inspect this later

**Comment by Tylerpizza11** [comment]
ok, idk what you meat by that.

**Comment by NightScript370** [comment]
The interface you used to upload "Source Code.7z" is the same interface you should use to actually upload the code. But if the point of this repo was to have an app in UDB under your name, well, sorry to disappoint but it's rejected.

All this app does is just read an `index.html` file (which can be done by GodMode9 or any other text reader, but then you wouldn't waste read cycles as this app does) and then when the R button is held, write a template HTML (which doesn't even confine to proper HTML standards, judging from that "//" comment).

I don't see any practical usecase, so I'll have to reject this.
