### ISSUE TITLE
Fixed Ikachan DS, compatible with TMFH

### ISSUE THREAD

**Issue by awkitsune** [Universal-Team/db#97]
### Title

Ikachan

### System(s)

DS

### Categories

Game

### Icon link

https://github.com/awkitsune/IkachanDS/blob/master/icon.bmp

### Long description

In this game you can play as a squid named Ikachan, who swims through a cave, meeting and helping other creatures.
The game is compatible with DS flashcards, NDS-Bootstrap and HiyaCFW home menu via TMFH

### Screenshots

![Start screen](https://user-images.githubusercontent.com/45891293/195907103-6456f3fa-53aa-4032-a8d2-97429fbba3af.png)
![Gameplay](https://user-images.githubusercontent.com/45891293/195907106-4cc85aef-4336-4068-87a6-0fa2b3b2f193.png)

### GitHub repository of the app

https://github.com/awkitsune/IkachanDS

### Author

awkitsune

### Short description

Game about squid

### Download page link

https://github.com/awkitsune/IkachanDS/releases/latest

### Version number

0.2.0

### Version title

v0.2.0

### Other notes

I want to work on this project that's the reason I want to publish it separately from original DS port

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Sorry about the delay, only just getting back to my GitHub notifications. Should this just replace the original DS port on U-DB or should there be both?

I like to avoid duplicates and outdated apps when possible for a better user experience browsing U-DB, but if both are/will have reasons to use them I'll leave both up.

**Comment by awkitsune** [comment]
Idk this version is perfectly compatible with Hiya while the old one does not, so in my opinion this one is better. And I'm planning to make some things to prevent loading hangs
