### ISSUE TITLE
add Sonic Mania to the shop

### ISSUE THREAD

**Issue by DDiEnVy** [Universal-Team/db#99]
### Title

Sonic Mania

### System(s)

3DS

### Categories

Game

### Image link

https://cdn.akamai.steamstatic.com/steam/apps/584400/capsule_616x353.jpg?t=1642416672

### Icon link

https://vignette.wikia.nocookie.net/sonic/images/9/96/Mania_Icon.JPG/revision/latest?cb=20171018101321

### Long description

[README.md](https://github.com/Universal-Team/db/files/9998348/README.md)

### Screenshots

https://gbatemp.net/data/attachments/324/324695-8d54a698a9415ab2127ecb0637dc71ce.jpg

### Author

SaturnSH2x2

### Short description

Sonic Mania (only N3DS works)

### Source code link

https://github.com/SaturnSH2x2/RSDKv5-Decompilation/tree/3ds-main

### Creation date

Sep-13-2022

### Last update date

09/13/22

### Download page link

https://github.com/SaturnSH2x2/RSDKv5-Decompilation/releases/tag/1.0

### Version number

1.0

### Version title

1.0

### Download link(s)

https://download1655.mediafire.com/7p0mwfyvaezg/12w1njnn7u9h9ci/SonicMania.cia

### Other notes

Go to the github to learn more about this port and many others!

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
Added in bb57d545f56522d85f71620f3ce70e3c617cad70
